module.exports = [
      { id: 1, name: 'ZA 1/2/3 - ØSTRE SØR-VARANGER'},
      { id: 2, name: 'ZB 5A - PASVIK'},
      { id: 3, name: 'ZC 4/5B -  VESTRE SØR-VARANGER'},
      { id: 4, name: 'ZD 6 - VÁRJJATNJÁRGA'},
      { id: 5, name: 'ZE 7 - RÁKKONJÁRGA'},
      { id: 6, name: 'ZF 9 - OLGGUT CORGAŠ/OARJE-DEATNU'},
      { id: 7, name: 'ØG TROLLHEIMEN'},
      { id: 8, name: 'UW 3 - ELGÅ'},
      { id: 9, name: 'UX 2 - RIAST/HYLLING'},
      { id: 10, name: 'UY 4 - FEMUND (VINTERDISTRIKT)'},
      { id: 11, name: 'UZ 1 - ESSAND'},
      { id: 17, name: 'ZG 13 - LÁGESDUOTTAR'},
      { id: 18, name: 'ZH 14 - SPIERTTANJÁRGA'},
      { id: 19, name: 'ZJ 14A - SPIERTTAGÁISÁ'},
      { id: 20, name: 'ZS 16 - KÁRÁŠJOGA OARJJABEALLI'},
      { id: 21, name: 'YA 19 - SÁLLAN'},
      { id: 22, name: 'YB 20 - FÁLÁ/KVALØY'},
      { id: 23, name: 'YC 21 - GEARRETNJÁRGA'},
      { id: 24, name: 'YD 22 - FIETTAR'},
      { id: 25, name: 'YE 23 - SEAINNUS/NÁVGGASTAT'},
      { id: 26, name: 'YF 24A - OARJE-SIEVJU'},
      { id: 27, name: 'YG 24B - NUORTA-SIEVJU'},
      { id: 28, name: 'XM 11T - RÁIDNÁ '},
      { id: 29, name: 'XR 33T - ITTUNJÁRGA'},
      { id: 30, name: 'XT 19/32T - IVGOLÁHKU'},
      { id: 31, name: 'YH 25 - STIERDNÁ'},
      { id: 32, name: 'YI 41 - BEASKÁDAS'},
      { id: 33, name: 'YJ 26 - LAKKONJÁRGA'},
      { id: 34, name: 'YK 27 - JOAHKONJÁRGA'},
      { id: 35, name: 'YL 28 - CUOKCAVUOTNA'},
      { id: 36, name: 'YM 29 - SEAKKESNJÁRGA JA SILDÁ'},
      { id: 37, name: 'YN 32 - SILVVETNJÁRGA'},
      { id: 38, name: 'YP 33 - SPALCA'},
      { id: 39, name: 'YX 40 - ORDA'},
      { id: 40, name: 'YR 34 - ÁBBORAŠŠA'},
      { id: 41, name: 'YS 35 - FÁVRROSORDA'},
      { id: 42, name: 'YT 36 - COHKOLAT'},
      { id: 43, name: 'YU 37 - SKÁRFVÁGGI'},
      { id: 44, name: 'YW 39 - ÁRDNI/GÁVVIR'},
      { id: 45, name: 'YY 42 - BEAHCEGEALLI'},
      { id: 46, name: 'XA 34 - KANSTADFJORD/VESTRE HINNØY'},
      { id: 47, name: 'XD 36 - TJELDØY'},
      { id: 48, name: 'XE 23 - KONGSVIKDALEN'},
      { id: 49, name: 'XG 22 - GROVFJORD'},
      { id: 50, name: 'XH 16 - SØR-SENJA'},
      { id: 51, name: 'XJ 15 - NORD-SENJA'},
      { id: 52, name: 'XK 14 - KVALØY'},
      { id: 53, name: 'XL 12 - RINGVASSØY'},
      { id: 54, name: 'XN 13 - REBBENESØY'},
      { id: 55, name: 'XØ 21 - GIELAS'},
      { id: 56, name: 'XP 10 - VANNØY'},
      { id: 57, name: 'XU 17/18 - TROMSDALEN'},
      { id: 58, name: 'XW 24 - BASSEVUOVDI'},
      { id: 59, name: 'XZ 20 - HJERTTIND'},
      { id: 60, name: 'WA 18 - VOENGELH-NJAARKE'},
      { id: 61, name: 'WB 20 - JILLEN-NJAARKE'},
      { id: 62, name: 'WD 19 - BYRKIJE'},
      { id: 63, name: 'WF 21 - RØSSÅGA/TOVEN'},
      { id: 64, name: 'WK 23 - HESTMANNEN/STRANDTINDENE'},
      { id: 65, name: 'WL 22 - ILDGRUBEN'},
      { id: 66, name: 'WN 24 - SALTFJELLET'},
      { id: 67, name: 'WP 25 - BALVATN'},
      { id: 68, name: 'WR 26 - DUOKTA'},
      { id: 69, name: 'WS 27 - STAJGGO/HÁBMER'},
      { id: 70, name: 'WX 28 - FROSTISEN'},
      { id: 71, name: 'WZ 29 - SKJOMEN'},
      { id: 72, name: 'VA 7 - GASKEN-LAANTE'},
      { id: 73, name: 'VF 8 - SKÆHKERE'},
      { id: 74, name: 'VG 9 - LÅARTE'},
      { id: 75, name: 'VJ 10 - TJÅEHKERE SIJTE'},
      { id: 76, name: 'VM 11 - ÅARJEL-NJAARKE'},
      { id: 77, name: 'VR 6 - FOVSEN-NJAARKE'},
      { id: 78, name: 'YY 30 A OARBEALLI'},
      { id: 79, name: 'YY 30 B GUOVDAJOHTOLAT'},
      { id: 80, name: 'YY 30 C NUORTABEALLI'},
      { id: 81, name: '17 KARASJOK ØSTRE VÅR/HØST/VINTERBEITE'}
];
