/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import {
  MatchResults,
} from '@stencil/router';

import {
  ReinApp as ReinApp
} from './components/rein-app/rein-app';

declare global {
  interface HTMLReinAppElement extends ReinApp, HTMLElement {
  }
  var HTMLReinAppElement: {
    prototype: HTMLReinAppElement;
    new (): HTMLReinAppElement;
  };
  interface HTMLElementTagNameMap {
    "rein-app": HTMLReinAppElement;
  }
  interface ElementTagNameMap {
    "rein-app": HTMLReinAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "rein-app": JSXElements.ReinAppAttributes;
    }
  }
  namespace JSXElements {
    export interface ReinAppAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  ReinArea as ReinArea
} from './components/rein-area/rein-area';

declare global {
  interface HTMLReinAreaElement extends ReinArea, HTMLElement {
  }
  var HTMLReinAreaElement: {
    prototype: HTMLReinAreaElement;
    new (): HTMLReinAreaElement;
  };
  interface HTMLElementTagNameMap {
    "rein-area": HTMLReinAreaElement;
  }
  interface ElementTagNameMap {
    "rein-area": HTMLReinAreaElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "rein-area": JSXElements.ReinAreaAttributes;
    }
  }
  namespace JSXElements {
    export interface ReinAreaAttributes extends HTMLAttributes {
      match?: MatchResults;
    }
  }
}


import {
  ReinAreas as ReinAreas
} from './components/rein-areas/rein-areas';

declare global {
  interface HTMLReinAreasElement extends ReinAreas, HTMLElement {
  }
  var HTMLReinAreasElement: {
    prototype: HTMLReinAreasElement;
    new (): HTMLReinAreasElement;
  };
  interface HTMLElementTagNameMap {
    "rein-areas": HTMLReinAreasElement;
  }
  interface ElementTagNameMap {
    "rein-areas": HTMLReinAreasElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "rein-areas": JSXElements.ReinAreasAttributes;
    }
  }
  namespace JSXElements {
    export interface ReinAreasAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  ReinDistrict as ReinDistrict
} from './components/rein-district/rein-district';

declare global {
  interface HTMLReinDistrictElement extends ReinDistrict, HTMLElement {
  }
  var HTMLReinDistrictElement: {
    prototype: HTMLReinDistrictElement;
    new (): HTMLReinDistrictElement;
  };
  interface HTMLElementTagNameMap {
    "rein-district": HTMLReinDistrictElement;
  }
  interface ElementTagNameMap {
    "rein-district": HTMLReinDistrictElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "rein-district": JSXElements.ReinDistrictAttributes;
    }
  }
  namespace JSXElements {
    export interface ReinDistrictAttributes extends HTMLAttributes {
      match?: MatchResults;
    }
  }
}

