(function (People) {
    People.register = [
        {
            id: 407,
            cutId: 519,
            district: 72,
            firstName: 'Anna A.',
            lastName: 'Stenfjell',
            address: '',
            place: 'Vuku',
            c1: 'b',
            c2: 'h',
            c3: '',
            c4: '',
            c5: 'q',
            c6: 'bb'
        },
        {
            id: 4372,
            cutId: 4881,
            district: 72,
            firstName: 'Sindre Fjelner Danielsen',
            lastName: 'Gundersen',
            address: 'Vergåsen 8',
            place: 'Hell',
            c1: 'a-',
            c2: 'th',
            c3: 'a-',
            c4: 'a-o',
            c5: '',
            c6: 'a-'
        },
        {
            id: 3872,
            cutId: 4595,
            district: 72,
            firstName: 'Silje Helen Danielsen',
            lastName: 'Gundersen',
            address: 'Vergåsen 8',
            place: 'Hell',
            c1: 'a',
            c2: 'thh',
            c3: 'a',
            c4: '',
            c5: '',
            c6: 'aa'
        },
        {
            id: 3873,
            cutId: 4596,
            district: 72,
            firstName: 'Joakim',
            lastName: 'Danielsen',
            address: '',
            place: '',
            c1: 'aan',
            c2: 't',
            c3: '',
            c4: '',
            c5: 'ph',
            c6: 'a'
        },
        {
            id: 36,
            cutId: 76,
            district: 72,
            firstName: 'Nils K.',
            lastName: 'Danielsen',
            address: '',
            place: 'Meråker',
            c1: 'a',
            c2: '',
            c3: 'aao',
            c4: '-y',
            c5: 'p',
            c6: ''
        },
        {
            id: 2175,
            cutId: 2475,
            district: 72,
            firstName: 'Sonja Kristine',
            lastName: 'Danielsen',
            address: '',
            place: 'Meråker',
            c1: 'a',
            c2: '',
            c3: 'aan',
            c4: 'aan',
            c5: '',
            c6: 'a'
        },
        {
            id: 89,
            cutId: 139,
            district: 72,
            firstName: 'Elias A.',
            lastName: 'Stenfjell',
            address: 'Sul',
            place: 'Vuku',
            c1: '',
            c2: 't',
            c3: 'n-',
            c4: 'n-',
            c5: '',
            c6: 'b'
        },
        {
            id: 98,
            cutId: 152,
            district: 72,
            firstName: 'Nils Sigvard',
            lastName: 'Danielsen',
            address: 'Nedre Møllenberg Gt 60',
            place: 'Trondheim',
            c1: '',
            c2: 'p',
            c3: 'd',
            c4: 'a-o',
            c5: '',
            c6: 'a-'
        },
        {
            id: 4582,
            cutId: 5100,
            district: 72,
            firstName: 'Elias Sammol Gaino',
            lastName: 'Danielsen',
            address: 'C/o Per Larsen Gaino, Lahppuluobbal',
            place: 'Kautokeino',
            c1: '',
            c2: 't',
            c3: 'aao',
            c4: 'a',
            c5: 'p',
            c6: ''
        },
        {
            id: 40,
            cutId: 80,
            district: 72,
            firstName: 'Elias Paul',
            lastName: 'Danielsen',
            address: '',
            place: '',
            c1: 'aan',
            c2: 't',
            c3: '',
            c4: '',
            c5: 'p',
            c6: 'a'
        },
        {
            id: 428,
            cutId: 546,
            district: 72,
            firstName: 'Lars Tony',
            lastName: 'Danielsen',
            address: 'C/o Nils K Danielsen',
            place: 'Meråker',
            c1: 'ag',
            c2: '',
            c3: 'ao',
            c4: '-y',
            c5: 'ph',
            c6: ''
        },
        {
            id: 411,
            cutId: 526,
            district: 72,
            firstName: 'Sonja Elise',
            lastName: 'Danielsen',
            address: '',
            place: 'Meråker',
            c1: 'aa',
            c2: '',
            c3: '',
            c4: 'a',
            c5: 'th',
            c6: 'a'
        },
        {
            id: 429,
            cutId: 548,
            district: 72,
            firstName: 'Ann-sofie D.',
            lastName: 'Gundersen',
            address: 'Vergåsen 8',
            place: 'Hell',
            c1: 'a',
            c2: 'th',
            c3: 'a',
            c4: '',
            c5: '',
            c6: 'aa'
        },
        {
            id: 4371,
            cutId: 4778,
            district: 72,
            firstName: 'Amalie-søøfe Charlotte',
            lastName: 'Gundersen',
            address: 'Vergåsen 8',
            place: 'Hell',
            c1: '',
            c2: 'h',
            c3: '',
            c4: '',
            c5: 'q',
            c6: ''
        },
        {
            id: 3819,
            cutId: 4546,
            district: 72,
            firstName: 'Tony Kristoffer',
            lastName: 'Danielsen',
            address: 'C/o Nils K Danilsen',
            place: 'Meråker',
            c1: 'an',
            c2: '',
            c3: 'ag',
            c4: '-y',
            c5: 'ph',
            c6: ''
        },
        {
            id: 4115,
            cutId: 4777,
            district: 72,
            firstName: 'Sonja Kristine',
            lastName: 'Danielsen',
            address: '',
            place: 'Meråker',
            c1: 'aa',
            c2: '',
            c3: 'nt',
            c4: 'n',
            c5: 't',
            c6: ''
        },
        {
            id: 4108,
            cutId: 4771,
            district: 72,
            firstName: 'Aina-lene Gaino',
            lastName: 'Danielsen',
            address: 'Møllebakken 1',
            place: 'Meråker',
            c1: 'n',
            c2: 't',
            c3: 'f',
            c4: '',
            c5: 'p',
            c6: 'a'
        },
        {
            id: 507,
            cutId: 629,
            district: 72,
            firstName: 'Stig Daniel',
            lastName: 'Danielsen',
            address: '',
            place: 'Meråker',
            c1: 'f',
            c2: '',
            c3: 'o',
            c4: '-y',
            c5: 'p',
            c6: ''
        },
        {
            id: 537,
            cutId: 663,
            district: 72,
            firstName: 'Ina Ristin',
            lastName: 'Gundersen',
            address: 'Vegåsen 8',
            place: 'Hell',
            c1: 'aa',
            c2: 'p',
            c3: '',
            c4: '',
            c5: '',
            c6: 'aaa'
        },
        {
            id: 79,
            cutId: 127,
            district: 72,
            firstName: 'Sofie',
            lastName: 'Stenfjell',
            address: 'C/o Snåsa Sykeheim',
            place: 'Snåsa',
            c1: 'a',
            c2: '',
            c3: 'o',
            c4: 'a',
            c5: 't',
            c6: 'a'
        },
        {
            id: 2158,
            cutId: 2464,
            district: 72,
            firstName: 'Linda Iren',
            lastName: 'Gundersen',
            address: 'Vergåsen 8',
            place: 'Hell',
            c1: 'a',
            c2: 'th',
            c3: 'a',
            c4: '',
            c5: '',
            c6: 'aaa'
        },
        {
            id: 95,
            cutId: 148,
            district: 72,
            firstName: 'Ann-marie',
            lastName: 'Stenfjell',
            address: 'C/o Møen, Øvre Gård',
            place: 'Ytterøy',
            c1: 'a',
            c2: 't',
            c3: 'a',
            c4: '',
            c5: 'h',
            c6: 'a'
        },
        {
            id: 2176,
            cutId: 4868,
            district: 73,
            firstName: 'Laila',
            lastName: 'Hætta',
            address: '',
            place: '',
            c1: '-d',
            c2: 'h',
            c3: '',
            c4: '',
            c5: 'p',
            c6: ''
        },
        {
            id: 3871,
            cutId: 4594,
            district: 73,
            firstName: 'Aina Lisa',
            lastName: 'Wilks',
            address: '',
            place: 'Snåsa',
            c1: 'aaa',
            c2: '',
            c3: '',
            c4: '',
            c5: 'j',
            c6: ''
        },
        {
            id: 325,
            cutId: 417,
            district: 73,
            firstName: 'Birgit Helen',
            lastName: 'Wilks',
            address: 'Weidemannsvei 35',
            place: 'Trondheim',
            c1: 'an',
            c2: '',
            c3: 'aa',
            c4: '',
            c5: 'h',
            c6: ''
        },
        {
            id: 423,
            cutId: 539,
            district: 73,
            firstName: 'Elin',
            lastName: 'Danielsen',
            address: '',
            place: 'Snåsa',
            c1: 'a',
            c2: 't',
            c3: '-d',
            c4: '',
            c5: '',
            c6: 'n'
        },
        {
            id: 4353,
            cutId: 4867,
            district: 73,
            firstName: 'Mathis Ivan',
            lastName: 'Hætta',
            address: '',
            place: 'Snåsa',
            c1: '',
            c2: 'h',
            c3: 'd',
            c4: '',
            c5: 'p',
            c6: 'a'
        },
        {
            id: 321,
            cutId: 412,
            district: 73,
            firstName: 'Eva Anette',
            lastName: 'Wilks',
            address: 'Hompen',
            place: 'Snåsa',
            c1: 'aan',
            c2: '',
            c3: 'a',
            c4: '',
            c5: 'h',
            c6: ''
        },
        {
            id: 2082,
            cutId: 2376,
            district: 73,
            firstName: 'Niklas A.',
            lastName: 'Hætta',
            address: '',
            place: '',
            c1: '',
            c2: 'h',
            c3: 'a',
            c4: '',
            c5: '',
            c6: 'f'
        },
        {
            id: 4409,
            cutId: 69,
            district: 73,
            firstName: 'Neila-issát Påve',
            lastName: 'Wilks',
            address: 'Berget',
            place: 'Snåsa',
            c1: 'a',
            c2: 'q',
            c3: '',
            c4: '',
            c5: 'j',
            c6: ''
        },
        {
            id: 2177,
            cutId: 2477,
            district: 73,
            firstName: 'Marit',
            lastName: 'Hætta',
            address: '',
            place: 'Snåsa',
            c1: 'd',
            c2: 'h',
            c3: '',
            c4: '',
            c5: 'q',
            c6: ''
        },
        {
            id: 68,
            cutId: 114,
            district: 73,
            firstName: 'Laila Gunilla',
            lastName: 'Wilks',
            address: '',
            place: 'Snåsa',
            c1: 'aaa',
            c2: 'q',
            c3: '',
            c4: '',
            c5: 'h',
            c6: ''
        },
        {
            id: 3795,
            cutId: 4521,
            district: 73,
            firstName: 'Maria Gunilla Påve',
            lastName: 'Wilks',
            address: 'Berget',
            place: 'Snåsa',
            c1: '',
            c2: 'q',
            c3: '',
            c4: 'g',
            c5: 'u',
            c6: 'ga'
        },
        {
            id: 4611,
            cutId: 5119,
            district: 73,
            firstName: 'Anne K.',
            lastName: 'Danielsen',
            address: 'Gifstad',
            place: 'Snåsa',
            c1: '-d',
            c2: 'gt-',
            c3: '',
            c4: '',
            c5: '',
            c6: 'na'
        },
        {
            id: 473,
            cutId: 596,
            district: 73,
            firstName: 'Johan',
            lastName: 'Hætta',
            address: '',
            place: 'Snåsa',
            c1: '',
            c2: 'h',
            c3: 'a',
            c4: '',
            c5: 'th',
            c6: ''
        },
        {
            id: 45,
            cutId: 85,
            district: 73,
            firstName: 'Anne K.',
            lastName: 'Danielsen',
            address: 'Gifstad',
            place: 'Snåsa',
            c1: '',
            c2: 't',
            c3: '-d',
            c4: 'a',
            c5: 'q',
            c6: 'a'
        },
        {
            id: 460,
            cutId: 573,
            district: 73,
            firstName: 'Katrine',
            lastName: 'Hætta',
            address: '',
            place: '',
            c1: '',
            c2: 'h',
            c3: 'd',
            c4: '',
            c5: 'p',
            c6: ''
        },
        {
            id: 4612,
            cutId: 5120,
            district: 73,
            firstName: 'Anne K.',
            lastName: 'Danielsen',
            address: 'Gifstad',
            place: 'Snåsa',
            c1: '',
            c2: 'gt',
            c3: '-d',
            c4: '',
            c5: '',
            c6: 'na'
        },
        {
            id: 426,
            cutId: 542,
            district: 73,
            firstName: 'Hanne-lena',
            lastName: 'Wilks',
            address: 'Berget',
            place: 'Snåsa',
            c1: '',
            c2: 'q',
            c3: 'a',
            c4: '',
            c5: 'h',
            c6: ''
        },
        {
            id: 4363,
            cutId: 4876,
            district: 73,
            firstName: 'Cecilie',
            lastName: 'Hætta',
            address: '',
            place: 'Snåsa',
            c1: 'a',
            c2: '',
            c3: 'o',
            c4: 'a',
            c5: '',
            c6: 'n'
        },
        {
            id: 4364,
            cutId: 4877,
            district: 73,
            firstName: 'Jorun Finsås',
            lastName: 'Hætta',
            address: '',
            place: 'Snåsa',
            c1: 'aa',
            c2: '',
            c3: 'o',
            c4: '',
            c5: 'qh',
            c6: ''
        },
        {
            id: 3860,
            cutId: 4582,
            district: 73,
            firstName: 'Anna-laila',
            lastName: 'Kappfjell',
            address: 'Gifstad',
            place: 'Snåsa',
            c1: 'c',
            c2: 'th',
            c3: '',
            c4: '',
            c5: '',
            c6: 'na'
        },
        {
            id: 4412,
            cutId: 4946,
            district: 73,
            firstName: 'Ole Frank',
            lastName: 'Hætta',
            address: '',
            place: 'Snåsa',
            c1: 'aa',
            c2: '',
            c3: 'o',
            c4: 'g',
            c5: '',
            c6: 'n'
        },
        {
            id: 3870,
            cutId: 4593,
            district: 73,
            firstName: 'Brita Sandvik',
            lastName: 'Wilks',
            address: 'Hompen',
            place: 'Snåsa',
            c1: '',
            c2: 'p',
            c3: 'aa',
            c4: '',
            c5: 'j',
            c6: ''
        },
        {
            id: 4411,
            cutId: 4945,
            district: 73,
            firstName: 'Anne K.',
            lastName: 'Danielsen',
            address: 'Gifstad',
            place: 'Snåsa',
            c1: '-d',
            c2: 't',
            c3: '',
            c4: '',
            c5: '',
            c6: 'na'
        },
        {
            id: 4212,
            cutId: 4866,
            district: 73,
            firstName: 'Naja K.',
            lastName: 'Hætta',
            address: '',
            place: 'Snåsa',
            c1: '-n',
            c2: 'j',
            c3: 'c-',
            c4: '',
            c5: 'p',
            c6: ''
        },
        {
            id: 2171,
            cutId: 2460,
            district: 73,
            firstName: 'Lisa',
            lastName: 'Hætta',
            address: '',
            place: 'Snåsa',
            c1: 'aa',
            c2: '',
            c3: 'o',
            c4: '',
            c5: 'th',
            c6: ''
        },
        {
            id: 3846,
            cutId: 4575,
            district: 73,
            firstName: 'Hans Erik',
            lastName: 'Sandvik',
            address: 'Hompen',
            place: 'Snåsa',
            c1: 'aan',
            c2: '',
            c3: '',
            c4: '',
            c5: 'j',
            c6: ''
        },
        {
            id: 2162,
            cutId: 2468,
            district: 73,
            firstName: 'Malin Kristine S.',
            lastName: 'Wilks',
            address: 'Hompen',
            place: 'Snåsa',
            c1: 'c',
            c2: '',
            c3: '',
            c4: '-n',
            c5: 'j',
            c6: ''
        },
        {
            id: 4116,
            cutId: 4780,
            district: 73,
            firstName: 'Jonas A.k.',
            lastName: 'Hætta',
            address: '',
            place: 'Snåsa',
            c1: 'a',
            c2: 'h',
            c3: 'a',
            c4: '',
            c5: 'p',
            c6: 'a'
        },
        {
            id: 531,
            cutId: 657,
            district: 73,
            firstName: 'Tomas A.',
            lastName: 'Danielsen',
            address: '',
            place: 'Snåsa',
            c1: '',
            c2: 't',
            c3: '-d',
            c4: '',
            c5: 'q',
            c6: 'aa'
        },
        {
            id: 4531,
            cutId: 5036,
            district: 73,
            firstName: 'Isak',
            lastName: 'Danielsen',
            address: 'Gifstad',
            place: 'Snåsa',
            c1: '-d',
            c2: 't',
            c3: '',
            c4: '',
            c5: 'q',
            c6: ''
        },
        {
            id: 4355,
            cutId: 4869,
            district: 74,
            firstName: 'Hanna Marie',
            lastName: 'Jåma',
            address: 'Agle',
            place: 'Snåsa',
            c1: 'an',
            c2: '',
            c3: '',
            c4: 'a',
            c5: '',
            c6: 'a'
        },
        {
            id: 432,
            cutId: 550,
            district: 74,
            firstName: 'Elle',
            lastName: 'Stenfjell',
            address: '',
            place: 'Snåsa',
            c1: 'a',
            c2: 'tg-',
            c3: '',
            c4: 'aa',
            c5: '',
            c6: 'a'
        },
        {
            id: 2163,
            cutId: 41,
            district: 74,
            firstName: 'Bengt Mattias',
            lastName: 'Jåma',
            address: 'Engum',
            place: 'Snåsa',
            c1: 'a',
            c2: 'u',
            c3: 'aa',
            c4: 'aa',
            c5: '',
            c6: ''
        },
        {
            id: 9,
            cutId: 47,
            district: 74,
            firstName: 'Bernt Arvid',
            lastName: 'Jåma',
            address: 'Omlia',
            place: 'Snåsa',
            c1: 'c',
            c2: '',
            c3: '',
            c4: 'aaa',
            c5: '',
            c6: ''
        },
        {
            id: 4535,
            cutId: 5040,
            district: 74,
            firstName: 'Jon Andreas',
            lastName: 'Stenfjell',
            address: 'Devika',
            place: 'Sørli',
            c1: 'a',
            c2: 't',
            c3: 'aa',
            c4: 'aa',
            c5: '',
            c6: 'a'
        },
        {
            id: 72,
            cutId: 118,
            district: 74,
            firstName: 'Evald',
            lastName: 'Stenfjell',
            address: 'Bostadlandet',
            place: 'Snåsa',
            c1: 'a',
            c2: '',
            c3: 'aa',
            c4: 'aa',
            c5: '',
            c6: 'a'
        },
        {
            id: 807,
            cutId: 974,
            district: 74,
            firstName: 'Bengt Åke',
            lastName: 'Jåma',
            address: 'Borg  3',
            place: 'Levanger',
            c1: '',
            c2: 't',
            c3: 'b',
            c4: 'b',
            c5: 'tho',
            c6: ''
        },
        {
            id: 4118,
            cutId: 4781,
            district: 74,
            firstName: 'Marja Linnea A. Gosen',
            lastName: 'Jåma',
            address: 'Omlia',
            place: 'Snåsa',
            c1: 'b',
            c2: '',
            c3: '',
            c4: 'bbb',
            c5: '',
            c6: ''
        },
        {
            id: 490,
            cutId: 613,
            district: 74,
            firstName: 'Maja Marie',
            lastName: 'Jåma',
            address: 'Agle',
            place: 'Snåsa',
            c1: 'an',
            c2: '',
            c3: '',
            c4: 'a',
            c5: 'u',
            c6: 'a'
        },
        {
            id: 4410,
            cutId: 2396,
            district: 74,
            firstName: 'dan',
            lastName: 'Jåma',
            address: '',
            place: '',
            c1: '',
            c2: 'i',
            c3: '',
            c4: 'aa',
            c5: '',
            c6: ''
        },
        {
            id: 2164,
            cutId: 408,
            district: 74,
            firstName: 'Jon Andreas',
            lastName: 'Stenfjell',
            address: 'Devika',
            place: 'Sørli',
            c1: 'a',
            c2: 'tg-',
            c3: '',
            c4: 'a',
            c5: '',
            c6: 'aa'
        },
        {
            id: 4356,
            cutId: 4870,
            district: 74,
            firstName: 'Johan Martin',
            lastName: 'Stenfjell',
            address: 'Åsgårdveien 9, Leil 218',
            place: 'Tromsø',
            c1: 'b',
            c2: '',
            c3: 'bg',
            c4: 'b',
            c5: '',
            c6: 'bb'
        },
        {
            id: 2157,
            cutId: 2463,
            district: 74,
            firstName: 'Malena J.',
            lastName: 'Stenfjell',
            address: 'Kjøpmannsgt. 34/a32',
            place: 'Trondheim',
            c1: 'b',
            c2: '',
            c3: 'o',
            c4: 'b',
            c5: 't',
            c6: 'b'
        },
        {
            id: 2172,
            cutId: 2462,
            district: 74,
            firstName: 'Britt Inger G.',
            lastName: 'Stenfjell',
            address: 'Bostadlandet',
            place: 'Snåsa',
            c1: '',
            c2: '',
            c3: 'a',
            c4: '',
            c5: 't',
            c6: 'aa'
        },
        {
            id: 2156,
            cutId: 2461,
            district: 74,
            firstName: 'Niila',
            lastName: 'Blind',
            address: 'Bostadlandet',
            place: 'Snåsa',
            c1: 'g',
            c2: '',
            c3: 'a',
            c4: '',
            c5: 't',
            c6: 'aa'
        },
        {
            id: 4413,
            cutId: 646,
            district: 74,
            firstName: 'Mats Jøran',
            lastName: 'Jåma',
            address: 'Agle',
            place: 'Snåsa',
            c1: 'an',
            c2: '',
            c3: '',
            c4: '',
            c5: 't',
            c6: 'a'
        },
        {
            id: 4367,
            cutId: 100,
            district: 74,
            firstName: 'Mats Jøran',
            lastName: 'Jåma',
            address: 'Agle',
            place: 'Snåsa',
            c1: 'an',
            c2: '',
            c3: 'g',
            c4: 'aaa',
            c5: '',
            c6: ''
        },
        {
            id: 4171,
            cutId: 601,
            district: 74,
            firstName: 'Jon Daniel',
            lastName: 'Jåma',
            address: '',
            place: 'Snåsa',
            c1: '',
            c2: 't',
            c3: 'b',
            c4: 'bo',
            c5: 't',
            c6: ''
        },
        {
            id: 4715,
            cutId: 5230,
            district: 74,
            firstName: 'Niila',
            lastName: 'Blind',
            address: 'Bostadlandet',
            place: 'Snåsa',
            c1: 'a',
            c2: '',
            c3: 'aa',
            c4: 'aa',
            c5: 't',
            c6: 'a'
        },
        {
            id: 54,
            cutId: 98,
            district: 74,
            firstName: 'Kjell Jøran',
            lastName: 'Jåma',
            address: 'Agle',
            place: 'Snåsa',
            c1: 'an',
            c2: '',
            c3: '',
            c4: 'aaa',
            c5: '',
            c6: ''
        },
        {
            id: 485,
            cutId: 608,
            district: 74,
            firstName: 'Anna Liisa',
            lastName: 'Jåma',
            address: 'Sandnes',
            place: 'Snåsa',
            c1: '',
            c2: 'q',
            c3: 'b',
            c4: 'b',
            c5: 'u',
            c6: ''
        },
        {
            id: 64,
            cutId: 105,
            district: 74,
            firstName: 'Arnt Erik',
            lastName: 'Jåma',
            address: '',
            place: 'Snåsa',
            c1: '-g',
            c2: 'p',
            c3: '',
            c4: 'o',
            c5: 't',
            c6: ''
        },
        {
            id: 371,
            cutId: 477,
            district: 75,
            firstName: 'ove',
            lastName: 'Jåma',
            address: 'Slottnes',
            place: 'Limingen',
            c1: 'aa',
            c2: 't',
            c3: 'o',
            c4: '',
            c5: 't',
            c6: ''
        },
        {
            id: 406,
            cutId: 518,
            district: 75,
            firstName: 'Algot',
            lastName: 'Jåma',
            address: 'Fjellbo',
            place: 'Limingen',
            c1: '-b',
            c2: '',
            c3: 'b',
            c4: '',
            c5: '',
            c6: 'n'
        },
        {
            id: 437,
            cutId: 556,
            district: 75,
            firstName: 'Ingvar',
            lastName: 'Jåma',
            address: 'Nyvikmoen',
            place: 'Limingen',
            c1: '',
            c2: 'thh',
            c3: '',
            c4: 'o',
            c5: '',
            c6: ''
        },
        {
            id: 3868,
            cutId: 4591,
            district: 75,
            firstName: 'Inger K.a.g.',
            lastName: 'Jåma',
            address: 'Nyvikmoen',
            place: 'Limingen',
            c1: 'bn',
            c2: '',
            c3: '',
            c4: 'bg',
            c5: 'u',
            c6: ''
        },
        {
            id: 3867,
            cutId: 4590,
            district: 75,
            firstName: 'Jon Olov',
            lastName: 'Jåma',
            address: 'Fjellbo',
            place: 'Limingen',
            c1: 'n',
            c2: '',
            c3: '',
            c4: '-d',
            c5: '',
            c6: 'aa'
        },
        {
            id: 379,
            cutId: 487,
            district: 75,
            firstName: 'Nils Ludvik',
            lastName: 'Jåma',
            address: 'V/maili Anita Jåma',
            place: 'Limingen',
            c1: '',
            c2: '',
            c3: 'o',
            c4: '',
            c5: 'u',
            c6: 'a'
        },
        {
            id: 2165,
            cutId: 484,
            district: 75,
            firstName: 'Marja Lisa',
            lastName: 'Thomasson',
            address: 'Barbo',
            place: 'Limingen',
            c1: 'b',
            c2: 't',
            c3: '-d',
            c4: 'bb',
            c5: 'u',
            c6: 'bb'
        },
        {
            id: 2081,
            cutId: 2375,
            district: 75,
            firstName: 'Mats Ailo',
            lastName: 'Jåma',
            address: 'Nyvikmoen',
            place: 'Limingen',
            c1: 'bn',
            c2: '',
            c3: '',
            c4: 'g',
            c5: '',
            c6: ''
        },
        {
            id: 4361,
            cutId: 914,
            district: 75,
            firstName: 'Mats',
            lastName: 'Joma',
            address: '',
            place: 'Limingen',
            c1: '',
            c2: 'u',
            c3: '',
            c4: 'bb',
            c5: 't',
            c6: ''
        },
        {
            id: 2173,
            cutId: 2473,
            district: 75,
            firstName: 'Nils Anders',
            lastName: 'Jåma',
            address: 'Nyvikmoen',
            place: 'Limingen',
            c1: 'bn',
            c2: '',
            c3: '',
            c4: 'o',
            c5: 't',
            c6: ''
        },
        {
            id: 2174,
            cutId: 2474,
            district: 75,
            firstName: 'ole',
            lastName: 'Nordfjell',
            address: '',
            place: 'Skorovatn',
            c1: 'aa',
            c2: 't',
            c3: 'o',
            c4: 'a',
            c5: 'p',
            c6: 'a'
        },
        {
            id: 528,
            cutId: 652,
            district: 75,
            firstName: 'Brita Iren',
            lastName: 'Thomasson',
            address: 'Barbo',
            place: 'Limingen',
            c1: 'bb',
            c2: '',
            c3: '',
            c4: '',
            c5: 't',
            c6: 'bb'
        },
        {
            id: 383,
            cutId: 490,
            district: 75,
            firstName: 'Anders',
            lastName: 'Joma',
            address: '',
            place: 'Skorovatn',
            c1: 'b',
            c2: 'q',
            c3: '',
            c4: '',
            c5: 't',
            c6: ''
        },
        {
            id: 4471,
            cutId: 5022,
            district: 75,
            firstName: 'Odd Bjørnar',
            lastName: 'Bjørkås',
            address: 'Devika',
            place: 'Sørli',
            c1: 'a-',
            c2: 'p',
            c3: '',
            c4: '',
            c5: 'u',
            c6: ''
        },
        {
            id: 1641,
            cutId: 1889,
            district: 75,
            firstName: 'Inger Marit',
            lastName: 'Eira-åhren',
            address: 'Røyrvikfoss 6',
            place: 'Limingen',
            c1: 'aa',
            c2: '',
            c3: 'm',
            c4: 'aa',
            c5: 'h',
            c6: 'd'
        },
        {
            id: 412,
            cutId: 527,
            district: 75,
            firstName: 'Peder Ludvik',
            lastName: 'Jåma',
            address: 'Slåttnes',
            place: 'Limingen',
            c1: 'aa',
            c2: 't',
            c3: 'o',
            c4: '',
            c5: 'ph',
            c6: ''
        },
        {
            id: 362,
            cutId: 464,
            district: 75,
            firstName: 'Aina',
            lastName: 'Steinfjell',
            address: '',
            place: 'Skorovatn',
            c1: 'aa',
            c2: 'u',
            c3: '',
            c4: '',
            c5: 'jk',
            c6: ''
        },
        {
            id: 398,
            cutId: 509,
            district: 75,
            firstName: 'Sigfred Hilmar',
            lastName: 'Jåma',
            address: '',
            place: 'Limingen',
            c1: '',
            c2: 'h',
            c3: 'b',
            c4: '',
            c5: '',
            c6: 'n'
        },
        {
            id: 4360,
            cutId: 4874,
            district: 75,
            firstName: 'Klemet I.',
            lastName: 'Jåma',
            address: 'Nyvikmoen',
            place: 'Limingen',
            c1: '',
            c2: 'thh',
            c3: '',
            c4: '',
            c5: 'j',
            c6: ''
        },
        {
            id: 4362,
            cutId: 4875,
            district: 75,
            firstName: 'Elin Kristina',
            lastName: 'Jåma',
            address: '',
            place: 'Limingen',
            c1: '-a',
            c2: 't',
            c3: '-a',
            c4: '',
            c5: 'q',
            c6: ''
        },
        {
            id: 4358,
            cutId: 4872,
            district: 75,
            firstName: 'Linda Mari',
            lastName: 'Jåma',
            address: '',
            place: 'Limingen',
            c1: 'g',
            c2: '',
            c3: 'o',
            c4: '',
            c5: 'u',
            c6: 'b'
        },
        {
            id: 4359,
            cutId: 4873,
            district: 75,
            firstName: 'Per Anders',
            lastName: 'Joma',
            address: '',
            place: 'Skorovatn',
            c1: '',
            c2: 'u',
            c3: '-g',
            c4: 'b',
            c5: 'p',
            c6: 'g'
        },
        {
            id: 4357,
            cutId: 4871,
            district: 75,
            firstName: 'Selma',
            lastName: 'Jåma',
            address: 'C/o John Henrik Jåma',
            place: 'Limingen',
            c1: 'b',
            c2: 't',
            c3: 'b',
            c4: 'b',
            c5: '',
            c6: ''
        },
        {
            id: 3864,
            cutId: 4587,
            district: 75,
            firstName: 'Eva Bendikke',
            lastName: 'Jåma',
            address: 'Slottnes',
            place: 'Limingen',
            c1: 'aa',
            c2: 't',
            c3: 'o',
            c4: '',
            c5: 't',
            c6: '-g'
        },
        {
            id: 4170,
            cutId: 4815,
            district: 75,
            firstName: 'Ida Marie Kristine Ingvarsdatter',
            lastName: 'Jåma',
            address: 'Nyvikmoen',
            place: 'Limingen',
            c1: 'bn',
            c2: '',
            c3: 'g',
            c4: 'bg',
            c5: 'u',
            c6: ''
        },
        {
            id: 3865,
            cutId: 4588,
            district: 75,
            firstName: 'Ellinor M.',
            lastName: 'Jåma',
            address: 'Bergsmo',
            place: 'Grong',
            c1: 'n',
            c2: '',
            c3: '',
            c4: '',
            c5: 'u',
            c6: 'a'
        },
        {
            id: 3866,
            cutId: 4589,
            district: 75,
            firstName: 'John Henrik',
            lastName: 'Jåma',
            address: 'Solstad',
            place: 'Limingen',
            c1: '',
            c2: 'u',
            c3: 'a',
            c4: 'aaa',
            c5: '',
            c6: ''
        },
        {
            id: 364,
            cutId: 466,
            district: 75,
            firstName: 'Nils P.',
            lastName: 'Joma',
            address: 'Valheim',
            place: 'Limingen',
            c1: '',
            c2: 'u',
            c3: 'bb',
            c4: '',
            c5: 'th',
            c6: ''
        },
        {
            id: 4107,
            cutId: 4770,
            district: 75,
            firstName: 'Marja Magdalena',
            lastName: 'Joma',
            address: 'Valheim',
            place: 'Limingen',
            c1: 'bb',
            c2: 'u',
            c3: '',
            c4: '',
            c5: 'th',
            c6: ''
        },
        {
            id: 770,
            cutId: 931,
            district: 75,
            firstName: 'Vilmi',
            lastName: 'Steinfjell',
            address: '',
            place: 'Skorovatn',
            c1: 'aa',
            c2: '',
            c3: 'o',
            c4: 'g',
            c5: 'u',
            c6: ''
        },
        {
            id: 538,
            cutId: 664,
            district: 75,
            firstName: 'Maili Anita',
            lastName: 'Jåma',
            address: 'Fjellstad',
            place: 'Grong',
            c1: '',
            c2: 't',
            c3: 'o',
            c4: '',
            c5: 'u',
            c6: 'a'
        },
        {
            id: 381,
            cutId: 489,
            district: 75,
            firstName: 'Nils Ole Oskar',
            lastName: 'Jåma',
            address: 'Solstad',
            place: 'Limingen',
            c1: '',
            c2: 'u',
            c3: 'ag',
            c4: 'aaa',
            c5: '',
            c6: ''
        },
        {
            id: 3845,
            cutId: 4574,
            district: 75,
            firstName: 'Maidi',
            lastName: 'Steinfjell',
            address: '',
            place: 'Skorovatn',
            c1: '',
            c2: 't',
            c3: 'b',
            c4: 'b',
            c5: 'u',
            c6: ''
        },
        {
            id: 375,
            cutId: 482,
            district: 75,
            firstName: 'Lars N.',
            lastName: 'Jåma',
            address: 'Nyvikmoen',
            place: 'Limingen',
            c1: 'bn',
            c2: '',
            c3: 'g',
            c4: 'g',
            c5: '',
            c6: ''
        },
        {
            id: 448,
            cutId: 565,
            district: 75,
            firstName: 'Lars Alvar',
            lastName: 'Thomasson',
            address: 'Barbo',
            place: 'Limingen',
            c1: 'n',
            c2: 't',
            c3: '',
            c4: 'c',
            c5: '',
            c6: 'c'
        },
        {
            id: 3803,
            cutId: 4532,
            district: 75,
            firstName: 'Lars Jonas',
            lastName: 'Åhrén',
            address: 'Røyrvikfoss 6',
            place: 'Limingen',
            c1: 'aa',
            c2: 'q',
            c3: '',
            c4: 'a',
            c5: 'u',
            c6: ''
        },
        {
            id: 3802,
            cutId: 4531,
            district: 75,
            firstName: 'Tomas Mikael',
            lastName: 'Thomasson',
            address: 'Barbo',
            place: 'Limingen',
            c1: 'a',
            c2: 'th',
            c3: 'a-',
            c4: '',
            c5: 'p',
            c6: ''
        },
        {
            id: 4530,
            cutId: 5035,
            district: 75,
            firstName: 'Elias Ole',
            lastName: 'Joma',
            address: '',
            place: 'Skorovatn',
            c1: '',
            c2: 'q',
            c3: 'a',
            c4: 'n',
            c5: '',
            c6: 'a'
        },
        {
            id: 4529,
            cutId: 5033,
            district: 75,
            firstName: 'Inga Emelie',
            lastName: 'Joma',
            address: '',
            place: 'Skorovatn',
            c1: 'aa',
            c2: 'j',
            c3: 'g',
            c4: '',
            c5: 'p',
            c6: ''
        },
        {
            id: 298,
            cutId: 373,
            district: 75,
            firstName: 'Knut Peder',
            lastName: 'Jåma',
            address: 'Solstad',
            place: 'Limingen',
            c1: '',
            c2: '',
            c3: 'o',
            c4: 'aaa',
            c5: '',
            c6: ''
        },
        {
            id: 4626,
            cutId: 5130,
            district: 75,
            firstName: 'Lars Jonas',
            lastName: 'Åhrén',
            address: 'Røyrvikfoss 6',
            place: 'Limingen',
            c1: 'aa',
            c2: 't',
            c3: 'o',
            c4: 'g',
            c5: 'ph',
            c6: ''
        },
        {
            id: 4608,
            cutId: 5117,
            district: 75,
            firstName: 'Berit Ellen G.',
            lastName: 'Jåma',
            address: 'Solstad',
            place: 'Limingen',
            c1: '-a',
            c2: 'thh',
            c3: '',
            c4: 'g',
            c5: 'thh',
            c6: 'aa'
        },
        {
            id: 3875,
            cutId: 4598,
            district: 76,
            firstName: 'Elle Karen Inga Johan Andersda',
            lastName: 'Oskal',
            address: '',
            place: 'Grong',
            c1: '',
            c2: '',
            c3: 'm',
            c4: 'a',
            c5: 'v',
            c6: 'a'
        },
        {
            id: 418,
            cutId: 534,
            district: 76,
            firstName: 'John Samuel',
            lastName: 'Anti',
            address: 'Harran',
            place: 'Grong',
            c1: 'g',
            c2: 'u',
            c3: 'a',
            c4: '',
            c5: 'th',
            c6: 'g'
        },
        {
            id: 2185,
            cutId: 2484,
            district: 76,
            firstName: 'Gunn',
            lastName: 'Toven',
            address: '977flått',
            place: 'Høylandet',
            c1: '',
            c2: '',
            c3: 'c',
            c4: '',
            c5: 't',
            c6: 'a'
        },
        {
            id: 3874,
            cutId: 4597,
            district: 76,
            firstName: 'Mikael Mathias',
            lastName: 'Anti',
            address: 'Kjelmoen',
            place: 'Trones',
            c1: 'l',
            c2: '',
            c3: '',
            c4: '',
            c5: 'u',
            c6: 'gg'
        },
        {
            id: 439,
            cutId: 559,
            district: 76,
            firstName: 'Inger Berit',
            lastName: 'Anti',
            address: 'Fiskumtrøa',
            place: 'Harran',
            c1: 'g',
            c2: 'u',
            c3: 'a',
            c4: 'a',
            c5: 'qh',
            c6: ''
        },
        {
            id: 304,
            cutId: 385,
            district: 76,
            firstName: 'Laila Marlene',
            lastName: 'Toven',
            address: 'C/o Ivar Toven, Alhusstrand',
            place: 'Namsos',
            c1: '',
            c2: 't',
            c3: '',
            c4: 'o',
            c5: 't',
            c6: 'a'
        },
        {
            id: 2166,
            cutId: 380,
            district: 76,
            firstName: 'Per Jonas Aksel',
            lastName: 'Toven',
            address: 'C/o Ivar Toven, Alhusstrand',
            place: 'Namsos',
            c1: '',
            c2: 'th',
            c3: 'a',
            c4: 'aa',
            c5: 'h',
            c6: ''
        },
        {
            id: 4366,
            cutId: 494,
            district: 76,
            firstName: 'Nils Johan',
            lastName: 'Anti',
            address: 'Kjelmoen',
            place: 'Trones',
            c1: 'l',
            c2: 'h',
            c3: '',
            c4: 'a',
            c5: 'u',
            c6: ''
        },
        {
            id: 790,
            cutId: 951,
            district: 76,
            firstName: 'Ellen Marie Anne',
            lastName: 'Anti',
            address: 'C/o Inger Berit Anti, Fiskumtrøa',
            place: 'Harran',
            c1: '',
            c2: 'u',
            c3: 'a',
            c4: '',
            c5: 'thh',
            c6: 'a'
        },
        {
            id: 792,
            cutId: 954,
            district: 76,
            firstName: 'Samuel Nils',
            lastName: 'Anti',
            address: '',
            place: '',
            c1: 'g',
            c2: 'u',
            c3: 'a',
            c4: '',
            c5: 't',
            c6: ''
        },
        {
            id: 2168,
            cutId: 957,
            district: 76,
            firstName: 'Ina Sofie',
            lastName: 'Jåma',
            address: 'Berget',
            place: 'Snåsa',
            c1: '',
            c2: 'p',
            c3: 'a',
            c4: '',
            c5: 'th',
            c6: 'a'
        },
        {
            id: 4352,
            cutId: 458,
            district: 76,
            firstName: 'Hans Jakob',
            lastName: 'Toven',
            address: '',
            place: 'Høylandet',
            c1: '',
            c2: 'p',
            c3: 'a',
            c4: 'a',
            c5: 'j',
            c6: 'a'
        },
        {
            id: 400,
            cutId: 511,
            district: 76,
            firstName: 'Albert',
            lastName: 'Jåma',
            address: 'Åsveien 15',
            place: 'Kolvereid',
            c1: 'a',
            c2: 'u',
            c3: '',
            c4: 'a',
            c5: 't',
            c6: 'aa'
        },
        {
            id: 2086,
            cutId: 2395,
            district: 76,
            firstName: 'Karen Magga',
            lastName: 'Anti',
            address: 'Harran',
            place: 'Grong',
            c1: '',
            c2: 'phh',
            c3: '',
            c4: '',
            c5: 'phh',
            c6: ''
        },
        {
            id: 352,
            cutId: 452,
            district: 76,
            firstName: 'Anna',
            lastName: 'Anti',
            address: 'Kautokeinoveien 24',
            place: 'Karasjok',
            c1: '',
            c2: 'qhh',
            c3: '',
            c4: '',
            c5: 'qhh',
            c6: ''
        },
        {
            id: 354,
            cutId: 455,
            district: 76,
            firstName: 'Lars',
            lastName: 'Toven',
            address: 'Flått',
            place: 'Høylandet',
            c1: 'a',
            c2: '',
            c3: 'z',
            c4: 'aa',
            c5: 't',
            c6: ''
        },
        {
            id: 397,
            cutId: 508,
            district: 76,
            firstName: 'Ivar',
            lastName: 'Toven',
            address: 'C/o  Pål Kristoffer Toven, Postboks 21',
            place: 'Namsskogan',
            c1: '',
            c2: 't',
            c3: 'aa',
            c4: 'aa',
            c5: 'p',
            c6: 'a'
        },
        {
            id: 4365,
            cutId: 4878,
            district: 76,
            firstName: 'Samuel Petter',
            lastName: 'Anti',
            address: 'Kjelmoen',
            place: 'Trones',
            c1: '-d',
            c2: '',
            c3: '',
            c4: 'a',
            c5: 'u',
            c6: 'a'
        },
        {
            id: 554,
            cutId: 681,
            district: 76,
            firstName: 'Rasmus Jon',
            lastName: 'Anti',
            address: '',
            place: 'Oppdal',
            c1: 'l',
            c2: 'h',
            c3: '',
            c4: '',
            c5: 'qhh',
            c6: ''
        },
        {
            id: 466,
            cutId: 584,
            district: 76,
            firstName: 'Helge Karlot',
            lastName: 'Anti',
            address: '',
            place: 'Høylandet',
            c1: '',
            c2: 'ph',
            c3: '',
            c4: '',
            c5: 'qh',
            c6: ''
        },
        {
            id: 2167,
            cutId: 506,
            district: 76,
            firstName: 'Arnt Ove',
            lastName: 'Toven',
            address: '',
            place: 'Høylandet',
            c1: '',
            c2: '',
            c3: 'z',
            c4: '',
            c5: '',
            c6: 'aa'
        },
        {
            id: 395,
            cutId: 505,
            district: 76,
            firstName: 'Anne Marit',
            lastName: 'Jåma',
            address: 'Rishaugen',
            place: 'Snåsa',
            c1: 'a',
            c2: 'h',
            c3: 'a',
            c4: '-d',
            c5: 't',
            c6: ''
        },
        {
            id: 524,
            cutId: 649,
            district: 76,
            firstName: 'Aslak Per',
            lastName: 'Anti',
            address: '',
            place: 'Høylandet',
            c1: 'l',
            c2: '',
            c3: 'g',
            c4: '',
            c5: 'qh',
            c6: ''
        },
        {
            id: 513,
            cutId: 639,
            district: 76,
            firstName: 'Jonill Margrethe',
            lastName: 'Anti',
            address: '',
            place: '',
            c1: '',
            c2: 'phh',
            c3: '',
            c4: 'a',
            c5: 'ph',
            c6: ''
        },
        {
            id: 2170,
            cutId: 2469,
            district: 76,
            firstName: 'Anders Ole',
            lastName: 'Anti',
            address: '',
            place: 'Høylandet',
            c1: '',
            c2: 'phh',
            c3: '',
            c4: '',
            c5: 'qhh',
            c6: ''
        },
        {
            id: 4441,
            cutId: 4533,
            district: 76,
            firstName: 'Pål Kristoffer',
            lastName: 'Toven',
            address: 'Holmen Pb 21',
            place: 'Namsskogan',
            c1: 'bb',
            c2: 't',
            c3: '',
            c4: 'b-',
            c5: '',
            c6: '-b'
        },
        {
            id: 300,
            cutId: 377,
            district: 76,
            firstName: 'Kjell Peder',
            lastName: 'Toven',
            address: 'Heimly',
            place: 'Trones',
            c1: '',
            c2: 'th',
            c3: 'aa',
            c4: '',
            c5: '',
            c6: 'c'
        },
        {
            id: 350,
            cutId: 449,
            district: 76,
            firstName: 'Rasmus Nils',
            lastName: 'Anti',
            address: 'Kautokeinovn 24',
            place: 'Karasjok',
            c1: 'l',
            c2: 'h',
            c3: '',
            c4: '',
            c5: 'u',
            c6: 'a'
        },
        {
            id: 440,
            cutId: 560,
            district: 76,
            firstName: 'Karen Anette Anti',
            lastName: 'Oskal',
            address: 'Box 57',
            place: 'Moen',
            c1: 'g',
            c2: 'u',
            c3: 'a',
            c4: '',
            c5: 'ti',
            c6: ''
        },
        {
            id: 342,
            cutId: 439,
            district: 77,
            firstName: 'Ingvald',
            lastName: 'Jåma',
            address: 'Gotvatnet',
            place: 'Follafoss',
            c1: '',
            c2: 'u',
            c3: 'bb',
            c4: 'b',
            c5: '',
            c6: 'bb'
        },
        {
            id: 4370,
            cutId: 531,
            district: 77,
            firstName: 'Petter',
            lastName: 'Haugen',
            address: 'Sjøåsen',
            place: 'Namdalseid',
            c1: 'b',
            c2: 't',
            c3: 'b',
            c4: '',
            c5: 'u',
            c6: ''
        },
        {
            id: 402,
            cutId: 513,
            district: 77,
            firstName: 'Siv Stormo',
            lastName: 'Holtan',
            address: 'Sprova',
            place: 'Beitstad',
            c1: '',
            c2: 't',
            c3: '',
            c4: 'ag',
            c5: 't',
            c6: ''
        },
        {
            id: 4351,
            cutId: 4865,
            district: 77,
            firstName: 'Berit',
            lastName: 'Jåma',
            address: 'Verrastranda',
            place: 'Follafoss',
            c1: '',
            c2: 'u',
            c3: 'b',
            c4: 'b',
            c5: '',
            c6: 'bb'
        },
        {
            id: 338,
            cutId: 435,
            district: 77,
            firstName: 'Naina',
            lastName: 'Jåma',
            address: '',
            place: 'Follafoss',
            c1: '',
            c2: 'u',
            c3: '',
            c4: '',
            c5: 'h',
            c6: 'bb'
        },
        {
            id: 2083,
            cutId: 2377,
            district: 77,
            firstName: 'Sissel S.',
            lastName: 'Holtan',
            address: 'Sjøåsen',
            place: 'Namdalseid',
            c1: 'a-',
            c2: 'u',
            c3: 'a-g',
            c4: '',
            c5: 'h',
            c6: ''
        },
        {
            id: 24,
            cutId: 64,
            district: 77,
            firstName: 'Terje',
            lastName: 'Haugen',
            address: 'Sjøåsen',
            place: 'Namdalseid',
            c1: 'b',
            c2: 'p',
            c3: '',
            c4: 'b',
            c5: '',
            c6: '-b'
        },
        {
            id: 2084,
            cutId: 2378,
            district: 77,
            firstName: 'Synneve',
            lastName: 'F¨jällberg',
            address: 'Fjellet',
            place: 'Follafoss',
            c1: 'aa',
            c2: '',
            c3: '',
            c4: 'b',
            c5: 'j',
            c6: ''
        },
        {
            id: 535,
            cutId: 660,
            district: 77,
            firstName: 'Tom Mathias',
            lastName: 'Jåma',
            address: '',
            place: 'Follafoss',
            c1: '',
            c2: 'u',
            c3: 'b',
            c4: 'b',
            c5: 'q',
            c6: '-b'
        },
        {
            id: 4369,
            cutId: 4862,
            district: 77,
            firstName: 'Anna Pavall',
            lastName: 'Holtan',
            address: 'Sjøåsen',
            place: 'Namdalseid',
            c1: '-b',
            c2: '',
            c3: 'b',
            c4: 'bb',
            c5: 'u',
            c6: ''
        },
        {
            id: 414,
            cutId: 529,
            district: 77,
            firstName: 'Arne',
            lastName: 'Holtan',
            address: 'Sjøåsen',
            place: 'Namdalseid',
            c1: 'a-',
            c2: 'u',
            c3: 'a-g',
            c4: '',
            c5: 't',
            c6: ''
        },
        {
            id: 2169,
            cutId: 525,
            district: 77,
            firstName: 'Elise Holtan Pavall',
            lastName: 'Årbogen',
            address: 'Sagavegen',
            place: 'Malm',
            c1: '',
            c2: 'p',
            c3: 'a',
            c4: '',
            c5: 'ht-',
            c6: 'a'
        },
        {
            id: 409,
            cutId: 521,
            district: 77,
            firstName: 'Leif Arne',
            lastName: 'Jåma',
            address: 'Gotvatnet',
            place: 'Follafoss',
            c1: '',
            c2: '',
            c3: 'gg',
            c4: '',
            c5: 'u',
            c6: ''
        },
        {
            id: 410,
            cutId: 522,
            district: 77,
            firstName: 'John Kristian',
            lastName: 'Jåma',
            address: 'Trongsundet',
            place: 'Mosvik',
            c1: 'aa',
            c2: '',
            c3: 'z-',
            c4: 'z-',
            c5: '',
            c6: 'aa'
        },
        {
            id: 3861,
            cutId: 4583,
            district: 77,
            firstName: 'Tor Daniel',
            lastName: 'Jåma',
            address: 'Gotvatnet',
            place: 'Follafoss',
            c1: '-a',
            c2: '',
            c3: 'a-',
            c4: '',
            c5: 'u',
            c6: 'g'
        },
        {
            id: 3863,
            cutId: 4586,
            district: 77,
            firstName: 'Lena',
            lastName: 'Haugen',
            address: 'Sjøåsen',
            place: 'Namdalseid',
            c1: '',
            c2: 'j',
            c3: 'g',
            c4: 'a',
            c5: 'p',
            c6: ''
        },
        {
            id: 404,
            cutId: 516,
            district: 77,
            firstName: 'Arvid',
            lastName: 'Jåma',
            address: 'Verrastranda',
            place: 'Follafoss',
            c1: '',
            c2: 'u',
            c3: 'b',
            c4: 'bb',
            c5: '',
            c6: 'b'
        },
        {
            id: 4368,
            cutId: 4584,
            district: 77,
            firstName: 'Ingrid Maria',
            lastName: 'Jåma',
            address: '',
            place: 'Follafoss',
            c1: '',
            c2: 'q',
            c3: 'b',
            c4: 'b',
            c5: 'j',
            c6: ''
        },
        {
            id: 3862,
            cutId: 4585,
            district: 77,
            firstName: 'John',
            lastName: 'Haugen',
            address: 'Sjøåsen',
            place: 'Namdalseid',
            c1: 'b',
            c2: 't',
            c3: 'b',
            c4: 'a',
            c5: 'j',
            c6: ''
        },
        {
            id: 2161,
            cutId: 2467,
            district: 77,
            firstName: 'John Kristoffer',
            lastName: 'Jåma',
            address: 'Fjellet',
            place: 'Follafoss',
            c1: '',
            c2: 'th',
            c3: 'a',
            c4: '',
            c5: 'p',
            c6: ''
        },
        {
            id: 2160,
            cutId: 2466,
            district: 77,
            firstName: 'Sara Emilie',
            lastName: 'Jåma',
            address: 'Gotvatnet',
            place: 'Follafoss',
            c1: '',
            c2: '',
            c3: 'bb',
            c4: 'b',
            c5: '',
            c6: 'bb'
        },
        {
            id: 2159,
            cutId: 2465,
            district: 77,
            firstName: 'Maja Kristine',
            lastName: 'Jåma',
            address: 'Fjellet',
            place: 'Follafoss',
            c1: 'a',
            c2: '',
            c3: '',
            c4: '',
            c5: 't',
            c6: 'a'
        },
        {
            id: 517,
            cutId: 643,
            district: 77,
            firstName: 'Sissel',
            lastName: 'Jåma',
            address: 'Verrastranda',
            place: 'Follafoss',
            c1: 'b-',
            c2: 'yt-',
            c3: 'b-',
            c4: '-y',
            c5: '',
            c6: ''
        },
        {
            id: 52,
            cutId: 92,
            district: 77,
            firstName: 'Erling',
            lastName: 'Holtan',
            address: 'Sjøåsen',
            place: 'Namdalseid',
            c1: 'a-',
            c2: 'u',
            c3: 'a-g',
            c4: '',
            c5: '',
            c6: 'a'
        }
    ];
}(REINMERKE.module('people')));
