(function(People) {
    People.register = [
{
    id: 2461,
    firstName: 'Niila',
    lastName: 'Blind',
    address: 'Bostadlandet',
    place: 'Snåsa',
    c1: 'g',
    c2: '',
    c3: 'a',
    c4: '',
    c5: 't',
    c6: 'aa',
},
{
    id: 2172,
    firstName: 'Britt Inger G.',
    lastName: 'Stenfjell',
    address: 'Bostadlandet',
    place: 'Snåsa',
    c1: '',
    c2: '',
    c3: 'a',
    c4: '',
    c5: 't',
    c6: 'aa',
},
{
    id: 2396,
    firstName: 'Dan',
    lastName: 'Jåma',
    address: '',
    place: '',
    c1: '',
    c2: 'i',
    c3: '',
    c4: 'aa',
    c5: '',
    c6: '',
},
{
    id: 646,
    firstName: 'Mats Jøran',
    lastName: 'Jåma',
    address: 'Agle',
    place: 'Snåsa',
    c1: 'an',
    c2: '',
    c3: '',
    c4: '',
    c5: 't',
    c6: 'a',
},
{
    id: 974,
    firstName: 'Bengt Åke',
    lastName: 'Jåma',
    address: 'Borg 3',
    place: 'Levanger',
    c1: '',
    c2: 't',
    c3: 'b',
    c4: 'b',
    c5: 'tho',
    c6: '',
},
{
    id: 2463,
    firstName: 'Malena J.',
    lastName: 'Stenfjell',
    address: 'Kjøpmannsgt. 34/A32',
    place: 'Trondheim',
    c1: 'b',
    c2: '',
    c3: 'o',
    c4: 'b',
    c5: 't',
    c6: 'b',
},
{
    id: 408,
    firstName: 'Jon Andreas',
    lastName: 'Stenfjell',
    address: 'Devika',
    place: 'Sørli',
    c1: 'a',
    c2: 'tg-',
    c3: '',
    c4: 'a',
    c5: '',
    c6: 'aa',
},
{
    id: 5230,
    firstName: 'Niila',
    lastName: 'Blind',
    address: 'Bostadlandet',
    place: 'Snåsa',
    c1: 'a',
    c2: '',
    c3: 'aa',
    c4: 'aa',
    c5: 't',
    c6: 'a',
}
];
}(REINMERKE.module('people')));
