[
{
    id: 407,
    district: 72,
    firstName: 'Anna A.',
    lastName: 'Stenfjell',
    address: '',
    place: 'Vuku',
    c1: 'b',
    c2: 'h',
    c3: '',
    c4: '',
    c5: 'q',
    c6: 'bb'
},
{
    id: 4372,
    district: 72,
    firstName: 'Sindre Fjelner Danielsen',
    lastName: 'Gundersen',
    address: 'Vergåsen 8',
    place: 'Hell',
    c1: 'a-',
    c2: 'th',
    c3: 'a-',
    c4: 'a-o',
    c5: '',
    c6: 'a-'
},
{
    id: 3872,
    district: 72,
    firstName: 'Silje Helen Danielsen',
    lastName: 'Gundersen',
    address: 'Vergåsen 8',
    place: 'Hell',
    c1: 'a',
    c2: 'thh',
    c3: 'a',
    c4: '',
    c5: '',
    c6: 'aa'
},
{
    id: 3873,
    district: 72,
    firstName: 'Joakim',
    lastName: 'Danielsen',
    address: '',
    place: '',
    c1: 'aan',
    c2: 't',
    c3: '',
    c4: '',
    c5: 'ph',
    c6: 'a'
},
{
    id: 36,
    district: 72,
    firstName: 'Nils K.',
    lastName: 'Danielsen',
    address: '',
    place: 'Meråker',
    c1: 'a',
    c2: '',
    c3: 'aao',
    c4: '-y',
    c5: 'p',
    c6: ''
},
{
    id: 2175,
    district: 72,
    firstName: 'Sonja Kristine',
    lastName: 'Danielsen',
    address: '',
    place: 'Meråker',
    c1: 'a',
    c2: '',
    c3: 'aan',
    c4: 'aan',
    c5: '',
    c6: 'a'
},
{
    id: 89,
    district: 72,
    firstName: 'Elias A.',
    lastName: 'Stenfjell',
    address: 'Sul',
    place: 'Vuku',
    c1: '',
    c2: 't',
    c3: 'n-',
    c4: 'n-',
    c5: '',
    c6: 'b'
},
{
    id: 98,
    district: 72,
    firstName: 'Nils Sigvard',
    lastName: 'Danielsen',
    address: 'Nedre Møllenberg Gt 60',
    place: 'Trondheim',
    c1: '',
    c2: 'p',
    c3: 'd',
    c4: 'a-o',
    c5: '',
    c6: 'a-'
},
{
    id: 4582,
    district: 72,
    firstName: 'Elias Sammol Gaino',
    lastName: 'Danielsen',
    address: 'C/o Per Larsen Gaino, Lahppuluobbal',
    place: 'Kautokeino',
    c1: '',
    c2: 't',
    c3: 'aao',
    c4: 'a',
    c5: 'p',
    c6: ''
},
{
    id: 40,
    district: 72,
    firstName: 'Elias Paul',
    lastName: 'Danielsen',
    address: '',
    place: '',
    c1: 'aan',
    c2: 't',
    c3: '',
    c4: '',
    c5: 'p',
    c6: 'a'
},
{
    id: 428,
    district: 72,
    firstName: 'Lars Tony',
    lastName: 'Danielsen',
    address: 'C/o Nils K Danielsen',
    place: 'Meråker',
    c1: 'ag',
    c2: '',
    c3: 'ao',
    c4: '-y',
    c5: 'ph',
    c6: ''
},
{
    id: 411,
    district: 72,
    firstName: 'Sonja Elise',
    lastName: 'Danielsen',
    address: '',
    place: 'Meråker',
    c1: 'aa',
    c2: '',
    c3: '',
    c4: 'a',
    c5: 'th',
    c6: 'a'
},
{
    id: 429,
    district: 72,
    firstName: 'Ann-sofie D.',
    lastName: 'Gundersen',
    address: 'Vergåsen 8',
    place: 'Hell',
    c1: 'a',
    c2: 'th',
    c3: 'a',
    c4: '',
    c5: '',
    c6: 'aa'
},
{
    id: 4371,
    district: 72,
    firstName: 'Amalie-søøfe Charlotte',
    lastName: 'Gundersen',
    address: 'Vergåsen 8',
    place: 'Hell',
    c1: '',
    c2: 'h',
    c3: '',
    c4: '',
    c5: 'q',
    c6: ''
},
{
    id: 3819,
    district: 72,
    firstName: 'Tony Kristoffer',
    lastName: 'Danielsen',
    address: 'C/o Nils K Danilsen',
    place: 'Meråker',
    c1: 'an',
    c2: '',
    c3: 'ag',
    c4: '-y',
    c5: 'ph',
    c6: ''
},
{
    id: 4115,
    district: 72,
    firstName: 'Sonja Kristine',
    lastName: 'Danielsen',
    address: '',
    place: 'Meråker',
    c1: 'aa',
    c2: '',
    c3: 'nt',
    c4: 'n',
    c5: 't',
    c6: ''
},
{
    id: 4108,
    district: 72,
    firstName: 'Aina-lene Gaino',
    lastName: 'Danielsen',
    address: 'Møllebakken 1',
    place: 'Meråker',
    c1: 'n',
    c2: 't',
    c3: 'f',
    c4: '',
    c5: 'p',
    c6: 'a'
},
{
    id: 507,
    district: 72,
    firstName: 'Stig Daniel',
    lastName: 'Danielsen',
    address: '',
    place: 'Meråker',
    c1: 'f',
    c2: '',
    c3: 'o',
    c4: '-y',
    c5: 'p',
    c6: ''
},
{
    id: 537,
    district: 72,
    firstName: 'Ina Ristin',
    lastName: 'Gundersen',
    address: 'Vegåsen 8',
    place: 'Hell',
    c1: 'aa',
    c2: 'p',
    c3: '',
    c4: '',
    c5: '',
    c6: 'aaa'
},
{
    id: 79,
    district: 72,
    firstName: 'Sofie',
    lastName: 'Stenfjell',
    address: 'C/o Snåsa Sykeheim',
    place: 'Snåsa',
    c1: 'a',
    c2: '',
    c3: 'o',
    c4: 'a',
    c5: 't',
    c6: 'a'
},
{
    id: 2158,
    district: 72,
    firstName: 'Linda Iren',
    lastName: 'Gundersen',
    address: 'Vergåsen 8',
    place: 'Hell',
    c1: 'a',
    c2: 'th',
    c3: 'a',
    c4: '',
    c5: '',
    c6: 'aaa'
},
{
    id: 95,
    district: 72,
    firstName: 'Ann-marie',
    lastName: 'Stenfjell',
    address: 'C/o Møen, Øvre Gård',
    place: 'Ytterøy',
    c1: 'a',
    c2: 't',
    c3: 'a',
    c4: '',
    c5: 'h',
    c6: 'a'
},
{
    id: 2176,
    district: 73,
    firstName: 'Laila',
    lastName: 'Hætta',
    address: '',
    place: '',
    c1: '-d',
    c2: 'h',
    c3: '',
    c4: '',
    c5: 'p',
    c6: ''
},
{
    id: 3871,
    district: 73,
    firstName: 'Aina Lisa',
    lastName: 'Wilks',
    address: '',
    place: 'Snåsa',
    c1: 'aaa',
    c2: '',
    c3: '',
    c4: '',
    c5: 'j',
    c6: ''
},
{
    id: 325,
    district: 73,
    firstName: 'Birgit Helen',
    lastName: 'Wilks',
    address: 'Weidemannsvei 35',
    place: 'Trondheim',
    c1: 'an',
    c2: '',
    c3: 'aa',
    c4: '',
    c5: 'h',
    c6: ''
},
{
    id: 423,
    district: 73,
    firstName: 'Elin',
    lastName: 'Danielsen',
    address: '',
    place: 'Snåsa',
    c1: 'a',
    c2: 't',
    c3: '-d',
    c4: '',
    c5: '',
    c6: 'n'
},
{
    id: 4353,
    district: 73,
    firstName: 'Mathis Ivan',
    lastName: 'Hætta',
    address: '',
    place: 'Snåsa',
    c1: '',
    c2: 'h',
    c3: 'd',
    c4: '',
    c5: 'p',
    c6: 'a'
},
{
    id: 321,
    district: 73,
    firstName: 'Eva Anette',
    lastName: 'Wilks',
    address: 'Hompen',
    place: 'Snåsa',
    c1: 'aan',
    c2: '',
    c3: 'a',
    c4: '',
    c5: 'h',
    c6: ''
},
{
    id: 2082,
    district: 73,
    firstName: 'Niklas A.',
    lastName: 'Hætta',
    address: '',
    place: '',
    c1: '',
    c2: 'h',
    c3: 'a',
    c4: '',
    c5: '',
    c6: 'f'
},
{
    id: 4409,
    district: 73,
    firstName: 'Neila-issát Påve',
    lastName: 'Wilks',
    address: 'Berget',
    place: 'Snåsa',
    c1: 'a',
    c2: 'q',
    c3: '',
    c4: '',
    c5: 'j',
    c6: ''
},
{
    id: 2177,
    district: 73,
    firstName: 'Marit',
    lastName: 'Hætta',
    address: '',
    place: 'Snåsa',
    c1: 'd',
    c2: 'h',
    c3: '',
    c4: '',
    c5: 'q',
    c6: ''
},
{
    id: 68,
    district: 73,
    firstName: 'Laila Gunilla',
    lastName: 'Wilks',
    address: '',
    place: 'Snåsa',
    c1: 'aaa',
    c2: 'q',
    c3: '',
    c4: '',
    c5: 'h',
    c6: ''
},
{
    id: 3795,
    district: 73,
    firstName: 'Maria Gunilla Påve',
    lastName: 'Wilks',
    address: 'Berget',
    place: 'Snåsa',
    c1: '',
    c2: 'q',
    c3: '',
    c4: 'g',
    c5: 'u',
    c6: 'ga'
},
{
    id: 4611,
    district: 73,
    firstName: 'Anne K.',
    lastName: 'Danielsen',
    address: 'Gifstad',
    place: 'Snåsa',
    c1: '-d',
    c2: 'gt-',
    c3: '',
    c4: '',
    c5: '',
    c6: 'na'
},
{
    id: 473,
    district: 73,
    firstName: 'Johan',
    lastName: '*hætta',
    address: '',
    place: 'Snåsa',
    c1: '',
    c2: 'h',
    c3: 'a',
    c4: '',
    c5: 'th',
    c6: ''
},
{
    id: 45,
    district: 73,
    firstName: 'Anne K.',
    lastName: 'Danielsen',
    address: 'Gifstad',
    place: 'Snåsa',
    c1: '',
    c2: 't',
    c3: '-d',
    c4: 'a',
    c5: 'q',
    c6: 'a'
},
{
    id: 460,
    district: 73,
    firstName: 'Katrine',
    lastName: 'Hætta',
    address: '',
    place: '',
    c1: '',
    c2: 'h',
    c3: 'd',
    c4: '',
    c5: 'p',
    c6: ''
},
{
    id: 4612,
    district: 73,
    firstName: 'Anne K.',
    lastName: 'Danielsen',
    address: 'Gifstad',
    place: 'Snåsa',
    c1: '',
    c2: 'gt',
    c3: '-d',
    c4: '',
    c5: '',
    c6: 'na'
},
{
    id: 426,
    district: 73,
    firstName: 'Hanne-lena',
    lastName: 'Wilks',
    address: 'Berget',
    place: 'Snåsa',
    c1: '',
    c2: 'q',
    c3: 'a',
    c4: '',
    c5: 'h',
    c6: ''
},
{
    id: 4363,
    district: 73,
    firstName: 'Cecilie',
    lastName: 'Hætta',
    address: '',
    place: 'Snåsa',
    c1: 'a',
    c2: '',
    c3: 'o',
    c4: 'a',
    c5: '',
    c6: 'n'
},
{
    id: 4364,
    district: 73,
    firstName: 'Jorun Finsås',
    lastName: 'Hætta',
    address: '',
    place: 'Snåsa',
    c1: 'aa',
    c2: '',
    c3: 'o',
    c4: '',
    c5: 'qh',
    c6: ''
},
{
    id: 3860,
    district: 73,
    firstName: 'Anna-laila',
    lastName: 'Kappfjell',
    address: 'Gifstad',
    place: 'Snåsa',
    c1: 'c',
    c2: 'th',
    c3: '',
    c4: '',
    c5: '',
    c6: 'na'
},
{
    id: 4412,
    district: 73,
    firstName: 'Ole Frank',
    lastName: 'Hætta',
    address: '',
    place: 'Snåsa',
    c1: 'aa',
    c2: '',
    c3: 'o',
    c4: 'g',
    c5: '',
    c6: 'n'
},
{
    id: 3870,
    district: 73,
    firstName: 'Brita Sandvik',
    lastName: 'Wilks',
    address: 'Hompen',
    place: 'Snåsa',
    c1: '',
    c2: 'p',
    c3: 'aa',
    c4: '',
    c5: 'j',
    c6: ''
},
{
    id: 4411,
    district: 73,
    firstName: 'Anne K.',
    lastName: 'Danielsen',
    address: 'Gifstad',
    place: 'Snåsa',
    c1: '-d',
    c2: 't',
    c3: '',
    c4: '',
    c5: '',
    c6: 'na'
},
{
    id: 4212,
    district: 73,
    firstName: 'Naja K.',
    lastName: 'Hætta',
    address: '',
    place: 'Snåsa',
    c1: '-n',
    c2: 'j',
    c3: 'c-',
    c4: '',
    c5: 'p',
    c6: ''
},
{
    id: 2171,
    district: 73,
    firstName: 'Lisa',
    lastName: 'Hætta',
    address: '',
    place: 'Snåsa',
    c1: 'aa',
    c2: '',
    c3: 'o',
    c4: '',
    c5: 'th',
    c6: ''
},
{
    id: 3846,
    district: 73,
    firstName: 'Hans Erik',
    lastName: 'Sandvik',
    address: 'Hompen',
    place: 'Snåsa',
    c1: 'aan',
    c2: '',
    c3: '',
    c4: '',
    c5: 'j',
    c6: ''
},
{
    id: 2162,
    district: 73,
    firstName: 'Malin Kristine S.',
    lastName: 'Wilks',
    address: 'Hompen',
    place: 'Snåsa',
    c1: 'c',
    c2: '',
    c3: '',
    c4: '-n',
    c5: 'j',
    c6: ''
},
{
    id: 4116,
    district: 73,
    firstName: 'Jonas A.k.',
    lastName: 'Hætta',
    address: '',
    place: 'Snåsa',
    c1: 'a',
    c2: 'h',
    c3: 'a',
    c4: '',
    c5: 'p',
    c6: 'a'
},
{
    id: 531,
    district: 73,
    firstName: 'Tomas A.',
    lastName: 'Danielsen',
    address: '',
    place: 'Snåsa',
    c1: '',
    c2: 't',
    c3: '-d',
    c4: '',
    c5: 'q',
    c6: 'aa'
},
{
    id: 4531,
    district: 73,
    firstName: 'Isak',
    lastName: 'Danielsen',
    address: 'Gifstad',
    place: 'Snåsa',
    c1: '-d',
    c2: 't',
    c3: '',
    c4: '',
    c5: 'q',
    c6: ''
},
{
    id: 4355,
    district: 74,
    firstName: 'Hanna Marie',
    lastName: 'Jåma',
    address: 'Agle',
    place: 'Snåsa',
    c1: 'an',
    c2: '',
    c3: '',
    c4: 'a',
    c5: '',
    c6: 'a'
},
{
    id: 432,
    district: 74,
    firstName: 'Elle',
    lastName: 'Stenfjell',
    address: '',
    place: 'Snåsa',
    c1: 'a',
    c2: 'tg-',
    c3: '',
    c4: 'aa',
    c5: '',
    c6: 'a'
},
{
    id: 2163,
    district: 74,
    firstName: 'Bengt Mattias',
    lastName: 'Jåma',
    address: 'Engum',
    place: 'Snåsa',
    c1: 'a',
    c2: 'u',
    c3: 'aa',
    c4: 'aa',
    c5: '',
    c6: ''
},
{
    id: 9,
    district: 74,
    firstName: 'Bernt Arvid',
    lastName: 'Jåma',
    address: 'Omlia',
    place: 'Snåsa',
    c1: 'c',
    c2: '',
    c3: '',
    c4: 'aaa',
    c5: '',
    c6: ''
},
{
    id: 4535,
    district: 74,
    firstName: 'Jon Andreas',
    lastName: 'Stenfjell',
    address: 'Devika',
    place: 'Sørli',
    c1: 'a',
    c2: 't',
    c3: 'aa',
    c4: 'aa',
    c5: '',
    c6: 'a'
},
{
    id: 72,
    district: 74,
    firstName: 'Evald',
    lastName: 'Stenfjell',
    address: 'Bostadlandet',
    place: 'Snåsa',
    c1: 'a',
    c2: '',
    c3: 'aa',
    c4: 'aa',
    c5: '',
    c6: 'a'
},
{
    id: 807,
    district: 74,
    firstName: 'Bengt Åke',
    lastName: 'Jåma',
    address: 'Borg  3',
    place: 'Levanger',
    c1: '',
    c2: 't',
    c3: 'b',
    c4: 'b',
    c5: 'tho',
    c6: ''
},
{
    id: 4118,
    district: 74,
    firstName: 'Marja Linnea A. Gosen',
    lastName: 'Jåma',
    address: 'Omlia',
    place: 'Snåsa',
    c1: 'b',
    c2: '',
    c3: '',
    c4: 'bbb',
    c5: '',
    c6: ''
},
{
    id: 490,
    district: 74,
    firstName: 'Maja Marie',
    lastName: 'Jåma',
    address: 'Agle',
    place: 'Snåsa',
    c1: 'an',
    c2: '',
    c3: '',
    c4: 'a',
    c5: 'u',
    c6: 'a'
},
{
    id: 4410,
    district: 74,
    firstName: 'dan',
    lastName: 'Jåma',
    address: '',
    place: '',
    c1: '',
    c2: 'i',
    c3: '',
    c4: 'aa',
    c5: '',
    c6: ''
},
{
    id: 2164,
    district: 74,
    firstName: 'Jon Andreas',
    lastName: 'Stenfjell',
    address: 'Devika',
    place: 'Sørli',
    c1: 'a',
    c2: 'tg-',
    c3: '',
    c4: 'a',
    c5: '',
    c6: 'aa'
},
{
    id: 4356,
    district: 74,
    firstName: 'Johan Martin',
    lastName: 'Stenfjell',
    address: 'Åsgårdveien 9, Leil 218',
    place: 'Tromsø',
    c1: 'b',
    c2: '',
    c3: 'bg',
    c4: 'b',
    c5: '',
    c6: 'bb'
},
{
    id: 2157,
    district: 74,
    firstName: 'Malena J.',
    lastName: 'Stenfjell',
    address: 'Kjøpmannsgt. 34/a32',
    place: 'Trondheim',
    c1: 'b',
    c2: '',
    c3: 'o',
    c4: 'b',
    c5: 't',
    c6: 'b'
},
{
    id: 2172,
    district: 74,
    firstName: 'Britt Inger G.',
    lastName: 'Stenfjell',
    address: 'Bostadlandet',
    place: 'Snåsa',
    c1: '',
    c2: '',
    c3: 'a',
    c4: '',
    c5: 't',
    c6: 'aa'
},
{
    id: 2156,
    district: 74,
    firstName: 'Niila',
    lastName: 'Blind',
    address: 'Bostadlandet',
    place: 'Snåsa',
    c1: 'g',
    c2: '',
    c3: 'a',
    c4: '',
    c5: 't',
    c6: 'aa'
},
{
    id: 4413,
    district: 74,
    firstName: 'Mats Jøran',
    lastName: 'Jåma',
    address: 'Agle',
    place: 'Snåsa',
    c1: 'an',
    c2: '',
    c3: '',
    c4: '',
    c5: 't',
    c6: 'a'
},
{
    id: 4367,
    district: 74,
    firstName: 'Mats Jøran',
    lastName: 'Jåma',
    address: 'Agle',
    place: 'Snåsa',
    c1: 'an',
    c2: '',
    c3: 'g',
    c4: 'aaa',
    c5: '',
    c6: ''
},
{
    id: 4171,
    district: 74,
    firstName: 'Jon Daniel',
    lastName: 'Jåma',
    address: '',
    place: 'Snåsa',
    c1: '',
    c2: 't',
    c3: 'b',
    c4: 'bo',
    c5: 't',
    c6: ''
},
{
    id: 4715,
    district: 74,
    firstName: 'Niila',
    lastName: 'Blind',
    address: 'Bostadlandet',
    place: 'Snåsa',
    c1: 'a',
    c2: '',
    c3: 'aa',
    c4: 'aa',
    c5: 't',
    c6: 'a'
},
{
    id: 54,
    district: 74,
    firstName: 'Kjell Jøran',
    lastName: 'Jåma',
    address: 'Agle',
    place: 'Snåsa',
    c1: 'an',
    c2: '',
    c3: '',
    c4: 'aaa',
    c5: '',
    c6: ''
},
{
    id: 485,
    district: 74,
    firstName: 'Anna Liisa',
    lastName: 'Jåma',
    address: 'Sandnes',
    place: 'Snåsa',
    c1: '',
    c2: 'q',
    c3: 'b',
    c4: 'b',
    c5: 'u',
    c6: ''
},
{
    id: 64,
    district: 74,
    firstName: 'Arnt Erik',
    lastName: 'Jåma',
    address: '',
    place: 'Snåsa',
    c1: '-g',
    c2: 'p',
    c3: '',
    c4: 'o',
    c5: 't',
    c6: ''
},
{
    id: 371,
    district: 75,
    firstName: 'ove',
    lastName: 'Jåma',
    address: 'Slottnes',
    place: 'Limingen',
    c1: 'aa',
    c2: 't',
    c3: 'o',
    c4: '',
    c5: 't',
    c6: ''
},
{
    id: 406,
    district: 75,
    firstName: 'Algot',
    lastName: 'Jåma',
    address: 'Fjellbo',
    place: 'Limingen',
    c1: '-b',
    c2: '',
    c3: 'b',
    c4: '',
    c5: '',
    c6: 'n'
},
{
    id: 437,
    district: 75,
    firstName: 'Ingvar',
    lastName: 'Jåma',
    address: 'Nyvikmoen',
    place: 'Limingen',
    c1: '',
    c2: 'thh',
    c3: '',
    c4: 'o',
    c5: '',
    c6: ''
},
{
    id: 3868,
    district: 75,
    firstName: 'Inger K.a.g.',
    lastName: 'Jåma',
    address: 'Nyvikmoen',
    place: 'Limingen',
    c1: 'bn',
    c2: '',
    c3: '',
    c4: 'bg',
    c5: 'u',
    c6: ''
},
{
    id: 3867,
    district: 75,
    firstName: 'Jon Olov',
    lastName: 'Jåma',
    address: 'Fjellbo',
    place: 'Limingen',
    c1: 'n',
    c2: '',
    c3: '',
    c4: '-d',
    c5: '',
    c6: 'aa'
},
{
    id: 379,
    district: 75,
    firstName: 'Nils Ludvik',
    lastName: 'Jåma',
    address: 'V/maili Anita Jåma',
    place: 'Limingen',
    c1: '',
    c2: '',
    c3: 'o',
    c4: '',
    c5: 'u',
    c6: 'a'
},
{
    id: 2165,
    district: 75,
    firstName: 'Marja Lisa',
    lastName: 'Thomasson',
    address: 'Barbo',
    place: 'Limingen',
    c1: 'b',
    c2: 't',
    c3: '-d',
    c4: 'bb',
    c5: 'u',
    c6: 'bb'
},
{
    id: 2081,
    district: 75,
    firstName: 'Mats Ailo',
    lastName: 'Jåma',
    address: 'Nyvikmoen',
    place: 'Limingen',
    c1: 'bn',
    c2: '',
    c3: '',
    c4: 'g',
    c5: '',
    c6: ''
},
{
    id: 4361,
    district: 75,
    firstName: 'Mats',
    lastName: 'Joma',
    address: '',
    place: 'Limingen',
    c1: '',
    c2: 'u',
    c3: '',
    c4: 'bb',
    c5: 't',
    c6: ''
},
{
    id: 2173,
    district: 75,
    firstName: 'Nils Anders',
    lastName: 'Jåma',
    address: 'Nyvikmoen',
    place: 'Limingen',
    c1: 'bn',
    c2: '',
    c3: '',
    c4: 'o',
    c5: 't',
    c6: ''
},
{
    id: 2174,
    district: 75,
    firstName: 'ole',
    lastName: 'Nordfjell',
    address: '',
    place: 'Skorovatn',
    c1: 'aa',
    c2: 't',
    c3: 'o',
    c4: 'a',
    c5: 'p',
    c6: 'a'
},
{
    id: 528,
    district: 75,
    firstName: 'Brita Iren',
    lastName: 'Thomasson',
    address: 'Barbo',
    place: 'Limingen',
    c1: 'bb',
    c2: '',
    c3: '',
    c4: '',
    c5: 't',
    c6: 'bb'
},
{
    id: 383,
    district: 75,
    firstName: 'Anders',
    lastName: 'Joma',
    address: '',
    place: 'Skorovatn',
    c1: 'b',
    c2: 'q',
    c3: '',
    c4: '',
    c5: 't',
    c6: ''
},
{
    id: 4471,
    district: 75,
    firstName: 'Odd Bjørnar',
    lastName: 'Bjørkås',
    address: 'Devika',
    place: 'Sørli',
    c1: 'a-',
    c2: 'p',
    c3: '',
    c4: '',
    c5: 'u',
    c6: ''
},
{
    id: 1641,
    district: 75,
    firstName: 'Inger Marit',
    lastName: 'Eira-åhren',
    address: 'Røyrvikfoss 6',
    place: 'Limingen',
    c1: 'aa',
    c2: '',
    c3: 'm',
    c4: 'aa',
    c5: 'h',
    c6: 'd'
},
{
    id: 412,
    district: 75,
    firstName: 'Peder Ludvik',
    lastName: 'Jåma',
    address: 'Slåttnes',
    place: 'Limingen',
    c1: 'aa',
    c2: 't',
    c3: 'o',
    c4: '',
    c5: 'ph',
    c6: ''
},
{
    id: 362,
    district: 75,
    firstName: 'Aina',
    lastName: 'Steinfjell',
    address: '',
    place: 'Skorovatn',
    c1: 'aa',
    c2: 'u',
    c3: '',
    c4: '',
    c5: 'jk',
    c6: ''
},
{
    id: 398,
    district: 75,
    firstName: 'Sigfred Hilmar',
    lastName: 'Jåma',
    address: '',
    place: 'Limingen',
    c1: '',
    c2: 'h',
    c3: 'b',
    c4: '',
    c5: '',
    c6: 'n'
},
{
    id: 4360,
    district: 75,
    firstName: 'Klemet I.',
    lastName: 'Jåma',
    address: 'Nyvikmoen',
    place: 'Limingen',
    c1: '',
    c2: 'thh',
    c3: '',
    c4: '',
    c5: 'j',
    c6: ''
},
{
    id: 4362,
    district: 75,
    firstName: 'Elin Kristina',
    lastName: 'Jåma',
    address: '',
    place: 'Limingen',
    c1: '-a',
    c2: 't',
    c3: '-a',
    c4: '',
    c5: 'q',
    c6: ''
},
{
    id: 4358,
    district: 75,
    firstName: 'Linda Mari',
    lastName: 'Jåma',
    address: '',
    place: 'Limingen',
    c1: 'g',
    c2: '',
    c3: 'o',
    c4: '',
    c5: 'u',
    c6: 'b'
},
{
    id: 4359,
    district: 75,
    firstName: 'Per Anders',
    lastName: 'Joma',
    address: '',
    place: 'Skorovatn',
    c1: '',
    c2: 'u',
    c3: '-g',
    c4: 'b',
    c5: 'p',
    c6: 'g'
},
{
    id: 4357,
    district: 75,
    firstName: 'Selma',
    lastName: 'Jåma',
    address: 'C/o John Henrik Jåma',
    place: 'Limingen',
    c1: 'b',
    c2: 't',
    c3: 'b',
    c4: 'b',
    c5: '',
    c6: ''
},
{
    id: 3864,
    district: 75,
    firstName: 'Eva Bendikke',
    lastName: 'Jåma',
    address: 'Slottnes',
    place: 'Limingen',
    c1: 'aa',
    c2: 't',
    c3: 'o',
    c4: '',
    c5: 't',
    c6: '-g'
},
{
    id: 4170,
    district: 75,
    firstName: 'Ida Marie Kristine Ingvarsdatter',
    lastName: 'Jåma',
    address: 'Nyvikmoen',
    place: 'Limingen',
    c1: 'bn',
    c2: '',
    c3: 'g',
    c4: 'bg',
    c5: 'u',
    c6: ''
},
{
    id: 3865,
    district: 75,
    firstName: 'Ellinor M.',
    lastName: 'Jåma',
    address: 'Bergsmo',
    place: 'Grong',
    c1: 'n',
    c2: '',
    c3: '',
    c4: '',
    c5: 'u',
    c6: 'a'
},
{
    id: 3866,
    district: 75,
    firstName: 'John Henrik',
    lastName: 'Jåma',
    address: 'Solstad',
    place: 'Limingen',
    c1: '',
    c2: 'u',
    c3: 'a',
    c4: 'aaa',
    c5: '',
    c6: ''
},
{
    id: 364,
    district: 75,
    firstName: 'Nils P.',
    lastName: 'Joma',
    address: 'Valheim',
    place: 'Limingen',
    c1: '',
    c2: 'u',
    c3: 'bb',
    c4: '',
    c5: 'th',
    c6: ''
},
{
    id: 4107,
    district: 75,
    firstName: 'Marja Magdalena',
    lastName: 'Joma',
    address: 'Valheim',
    place: 'Limingen',
    c1: 'bb',
    c2: 'u',
    c3: '',
    c4: '',
    c5: 'th',
    c6: ''
},
{
    id: 770,
    district: 75,
    firstName: 'Vilmi',
    lastName: 'Steinfjell',
    address: '',
    place: 'Skorovatn',
    c1: 'aa',
    c2: '',
    c3: 'o',
    c4: 'g',
    c5: 'u',
    c6: ''
},
{
    id: 538,
    district: 75,
    firstName: 'Maili Anita',
    lastName: 'Jåma',
    address: 'Fjellstad',
    place: 'Grong',
    c1: '',
    c2: 't',
    c3: 'o',
    c4: '',
    c5: 'u',
    c6: 'a'
},
{
    id: 381,
    district: 75,
    firstName: 'Nils Ole Oskar',
    lastName: 'Jåma',
    address: 'Solstad',
    place: 'Limingen',
    c1: '',
    c2: 'u',
    c3: 'ag',
    c4: 'aaa',
    c5: '',
    c6: ''
},
{
    id: 3845,
    district: 75,
    firstName: 'Maidi',
    lastName: 'Steinfjell',
    address: '',
    place: 'Skorovatn',
    c1: '',
    c2: 't',
    c3: 'b',
    c4: 'b',
    c5: 'u',
    c6: ''
},
{
    id: 375,
    district: 75,
    firstName: 'Lars N.',
    lastName: '*jåma',
    address: 'Nyvikmoen',
    place: 'Limingen',
    c1: 'bn',
    c2: '',
    c3: 'g',
    c4: 'g',
    c5: '',
    c6: ''
},
{
    id: 448,
    district: 75,
    firstName: 'Lars Alvar',
    lastName: 'Thomasson',
    address: 'Barbo',
    place: 'Limingen',
    c1: 'n',
    c2: 't',
    c3: '',
    c4: 'c',
    c5: '',
    c6: 'c'
},
{
    id: 3803,
    district: 75,
    firstName: 'Lars Jonas',
    lastName: 'Åhrén',
    address: 'Røyrvikfoss 6',
    place: 'Limingen',
    c1: 'aa',
    c2: 'q',
    c3: '',
    c4: 'a',
    c5: 'u',
    c6: ''
},
{
    id: 3802,
    district: 75,
    firstName: 'Tomas Mikael',
    lastName: 'Thomasson',
    address: 'Barbo',
    place: 'Limingen',
    c1: 'a',
    c2: 'th',
    c3: 'a-',
    c4: '',
    c5: 'p',
    c6: ''
},
{
    id: 4530,
    district: 75,
    firstName: 'Elias Ole',
    lastName: 'Joma',
    address: '',
    place: 'Skorovatn',
    c1: '',
    c2: 'q',
    c3: 'a',
    c4: 'n',
    c5: '',
    c6: 'a'
},
{
    id: 4529,
    district: 75,
    firstName: 'Inga Emelie',
    lastName: 'Joma',
    address: '',
    place: 'Skorovatn',
    c1: 'aa',
    c2: 'j',
    c3: 'g',
    c4: '',
    c5: 'p',
    c6: ''
},
{
    id: 298,
    district: 75,
    firstName: 'Knut Peder',
    lastName: 'Jåma',
    address: 'Solstad',
    place: 'Limingen',
    c1: '',
    c2: '',
    c3: 'o',
    c4: 'aaa',
    c5: '',
    c6: ''
},
{
    id: 4626,
    district: 75,
    firstName: 'Lars Jonas',
    lastName: 'Åhrén',
    address: 'Røyrvikfoss 6',
    place: 'Limingen',
    c1: 'aa',
    c2: 't',
    c3: 'o',
    c4: 'g',
    c5: 'ph',
    c6: ''
},
{
    id: 4608,
    district: 75,
    firstName: 'Berit Ellen G.',
    lastName: 'Jåma',
    address: 'Solstad',
    place: 'Limingen',
    c1: '-a',
    c2: 'thh',
    c3: '',
    c4: 'g',
    c5: 'thh',
    c6: 'aa'
},
{
    id: 3875,
    district: 76,
    firstName: 'Elle Karen Inga Johan Andersda',
    lastName: 'Oskal',
    address: '',
    place: 'Grong',
    c1: '',
    c2: '',
    c3: 'm',
    c4: 'a',
    c5: 'v',
    c6: 'a'
},
{
    id: 418,
    district: 76,
    firstName: 'John Samuel',
    lastName: 'Anti',
    address: 'Harran',
    place: 'Grong',
    c1: 'g',
    c2: 'u',
    c3: 'a',
    c4: '',
    c5: 'th',
    c6: 'g'
},
{
    id: 2185,
    district: 76,
    firstName: 'Gunn',
    lastName: 'Toven',
    address: '977flått',
    place: 'Høylandet',
    c1: '',
    c2: '',
    c3: 'c',
    c4: '',
    c5: 't',
    c6: 'a'
},
{
    id: 3874,
    district: 76,
    firstName: 'Mikael Mathias',
    lastName: 'Anti',
    address: 'Kjelmoen',
    place: 'Trones',
    c1: 'l',
    c2: '',
    c3: '',
    c4: '',
    c5: 'u',
    c6: 'gg'
},
{
    id: 439,
    district: 76,
    firstName: 'Inger Berit',
    lastName: 'Anti',
    address: 'Fiskumtrøa',
    place: 'Harran',
    c1: 'g',
    c2: 'u',
    c3: 'a',
    c4: 'a',
    c5: 'qh',
    c6: ''
},
{
    id: 304,
    district: 76,
    firstName: 'Laila Marlene',
    lastName: 'Toven',
    address: 'C/o Ivar Toven, Alhusstrand',
    place: 'Namsos',
    c1: '',
    c2: 't',
    c3: '',
    c4: 'o',
    c5: 't',
    c6: 'a'
},
{
    id: 2166,
    district: 76,
    firstName: 'Per Jonas Aksel',
    lastName: 'Toven',
    address: 'C/o Ivar Toven, Alhusstrand',
    place: 'Namsos',
    c1: '',
    c2: 'th',
    c3: 'a',
    c4: 'aa',
    c5: 'h',
    c6: ''
},
{
    id: 4366,
    district: 76,
    firstName: 'Nils Johan',
    lastName: 'Anti',
    address: 'Kjelmoen',
    place: 'Trones',
    c1: 'l',
    c2: 'h',
    c3: '',
    c4: 'a',
    c5: 'u',
    c6: ''
},
{
    id: 790,
    district: 76,
    firstName: 'Ellen Marie Anne',
    lastName: 'Anti',
    address: 'C/o Inger Berit Anti, Fiskumtrøa',
    place: 'Harran',
    c1: '',
    c2: 'u',
    c3: 'a',
    c4: '',
    c5: 'thh',
    c6: 'a'
},
{
    id: 792,
    district: 76,
    firstName: 'Samuel Nils',
    lastName: 'Anti',
    address: '',
    place: '',
    c1: 'g',
    c2: 'u',
    c3: 'a',
    c4: '',
    c5: 't',
    c6: ''
},
{
    id: 2168,
    district: 76,
    firstName: 'Ina Sofie',
    lastName: 'Jåma',
    address: 'Berget',
    place: 'Snåsa',
    c1: '',
    c2: 'p',
    c3: 'a',
    c4: '',
    c5: 'th',
    c6: 'a'
},
{
    id: 4352,
    district: 76,
    firstName: 'Hans Jakob',
    lastName: 'Toven',
    address: '',
    place: 'Høylandet',
    c1: '',
    c2: 'p',
    c3: 'a',
    c4: 'a',
    c5: 'j',
    c6: 'a'
},
{
    id: 400,
    district: 76,
    firstName: 'Albert',
    lastName: 'Jåma',
    address: 'Åsveien 15',
    place: 'Kolvereid',
    c1: 'a',
    c2: 'u',
    c3: '',
    c4: 'a',
    c5: 't',
    c6: 'aa'
},
{
    id: 2086,
    district: 76,
    firstName: 'Karen Magga',
    lastName: 'Anti',
    address: 'Harran',
    place: 'Grong',
    c1: '',
    c2: 'phh',
    c3: '',
    c4: '',
    c5: 'phh',
    c6: ''
},
{
    id: 352,
    district: 76,
    firstName: 'Anna',
    lastName: 'Anti',
    address: 'Kautokeinoveien 24',
    place: 'Karasjok',
    c1: '',
    c2: 'qhh',
    c3: '',
    c4: '',
    c5: 'qhh',
    c6: ''
},
{
    id: 354,
    district: 76,
    firstName: 'Lars',
    lastName: 'Toven',
    address: 'Flått',
    place: 'Høylandet',
    c1: 'a',
    c2: '',
    c3: 'z',
    c4: 'aa',
    c5: 't',
    c6: ''
},
{
    id: 397,
    district: 76,
    firstName: 'Ivar',
    lastName: 'Toven',
    address: 'C/o  Pål Kristoffer Toven, Postboks 21',
    place: 'Namsskogan',
    c1: '',
    c2: 't',
    c3: 'aa',
    c4: 'aa',
    c5: 'p',
    c6: 'a'
},
{
    id: 4365,
    district: 76,
    firstName: 'Samuel Petter',
    lastName: 'Anti',
    address: 'Kjelmoen',
    place: 'Trones',
    c1: '-d',
    c2: '',
    c3: '',
    c4: 'a',
    c5: 'u',
    c6: 'a'
},
{
    id: 554,
    district: 76,
    firstName: 'Rasmus Jon',
    lastName: 'Anti',
    address: '',
    place: 'Oppdal',
    c1: 'l',
    c2: 'h',
    c3: '',
    c4: '',
    c5: 'qhh',
    c6: ''
},
{
    id: 466,
    district: 76,
    firstName: 'Helge Karlot',
    lastName: 'Anti',
    address: '',
    place: 'Høylandet',
    c1: '',
    c2: 'ph',
    c3: '',
    c4: '',
    c5: 'qh',
    c6: ''
},
{
    id: 2167,
    district: 76,
    firstName: 'Arnt Ove',
    lastName: 'Toven',
    address: '',
    place: 'Høylandet',
    c1: '',
    c2: '',
    c3: 'z',
    c4: '',
    c5: '',
    c6: 'aa'
},
{
    id: 395,
    district: 76,
    firstName: 'Anne Marit',
    lastName: 'Jåma',
    address: 'Rishaugen',
    place: 'Snåsa',
    c1: 'a',
    c2: 'h',
    c3: 'a',
    c4: '-d',
    c5: 't',
    c6: ''
},
{
    id: 524,
    district: 76,
    firstName: 'Aslak Per',
    lastName: 'Anti',
    address: '',
    place: 'Høylandet',
    c1: 'l',
    c2: '',
    c3: 'g',
    c4: '',
    c5: 'qh',
    c6: ''
},
{
    id: 513,
    district: 76,
    firstName: 'Jonill Margrethe',
    lastName: 'Anti',
    address: '',
    place: '',
    c1: '',
    c2: 'phh',
    c3: '',
    c4: 'a',
    c5: 'ph',
    c6: ''
},
{
    id: 2170,
    district: 76,
    firstName: 'Anders Ole',
    lastName: 'Anti',
    address: '',
    place: 'Høylandet',
    c1: '',
    c2: 'phh',
    c3: '',
    c4: '',
    c5: 'qhh',
    c6: ''
},
{
    id: 4441,
    district: 76,
    firstName: 'Pål Kristoffer',
    lastName: 'Toven',
    address: 'Holmen Pb 21',
    place: 'Namsskogan',
    c1: 'bb',
    c2: 't',
    c3: '',
    c4: 'b-',
    c5: '',
    c6: '-b'
},
{
    id: 300,
    district: 76,
    firstName: 'Kjell Peder',
    lastName: 'Toven',
    address: 'Heimly',
    place: 'Trones',
    c1: '',
    c2: 'th',
    c3: 'aa',
    c4: '',
    c5: '',
    c6: 'c'
},
{
    id: 350,
    district: 76,
    firstName: 'Rasmus Nils',
    lastName: 'Anti',
    address: 'Kautokeinovn 24',
    place: 'Karasjok',
    c1: 'l',
    c2: 'h',
    c3: '',
    c4: '',
    c5: 'u',
    c6: 'a'
},
{
    id: 440,
    district: 76,
    firstName: 'Karen Anette Anti',
    lastName: 'Oskal',
    address: 'Box 57',
    place: 'Moen',
    c1: 'g',
    c2: 'u',
    c3: 'a',
    c4: '',
    c5: 'ti',
    c6: ''
},
{
    id: 342,
    district: 77,
    firstName: 'Ingvald',
    lastName: 'Jåma',
    address: 'Gotvatnet',
    place: 'Follafoss',
    c1: '',
    c2: 'u',
    c3: 'bb',
    c4: 'b',
    c5: '',
    c6: 'bb'
},
{
    id: 4370,
    district: 77,
    firstName: 'Petter',
    lastName: 'Haugen',
    address: 'Sjøåsen',
    place: 'Namdalseid',
    c1: 'b',
    c2: 't',
    c3: 'b',
    c4: '',
    c5: 'u',
    c6: ''
},
{
    id: 402,
    district: 77,
    firstName: 'Siv Stormo',
    lastName: 'Holtan',
    address: 'Sprova',
    place: 'Beitstad',
    c1: '',
    c2: 't',
    c3: '',
    c4: 'ag',
    c5: 't',
    c6: ''
},
{
    id: 4351,
    district: 77,
    firstName: 'Berit',
    lastName: 'Jåma',
    address: 'Verrastranda',
    place: 'Follafoss',
    c1: '',
    c2: 'u',
    c3: 'b',
    c4: 'b',
    c5: '',
    c6: 'bb'
},
{
    id: 338,
    district: 77,
    firstName: 'Naina',
    lastName: 'Jåma',
    address: '',
    place: 'Follafoss',
    c1: '',
    c2: 'u',
    c3: '',
    c4: '',
    c5: 'h',
    c6: 'bb'
},
{
    id: 2083,
    district: 77,
    firstName: 'Sissel S.',
    lastName: 'Holtan',
    address: 'Sjøåsen',
    place: 'Namdalseid',
    c1: 'a-',
    c2: 'u',
    c3: 'a-g',
    c4: '',
    c5: 'h',
    c6: ''
},
{
    id: 24,
    district: 77,
    firstName: 'Terje',
    lastName: 'Haugen',
    address: 'Sjøåsen',
    place: 'Namdalseid',
    c1: 'b',
    c2: 'p',
    c3: '',
    c4: 'b',
    c5: '',
    c6: '-b'
},
{
    id: 2084,
    district: 77,
    firstName: 'Synneve',
    lastName: 'F¨jällberg',
    address: 'Fjellet',
    place: 'Follafoss',
    c1: 'aa',
    c2: '',
    c3: '',
    c4: 'b',
    c5: 'j',
    c6: ''
},
{
    id: 535,
    district: 77,
    firstName: 'Tom Mathias',
    lastName: 'Jåma',
    address: '',
    place: 'Follafoss',
    c1: '',
    c2: 'u',
    c3: 'b',
    c4: 'b',
    c5: 'q',
    c6: '-b'
},
{
    id: 4369,
    district: 77,
    firstName: 'Anna Pavall',
    lastName: 'Holtan',
    address: 'Sjøåsen',
    place: 'Namdalseid',
    c1: '-b',
    c2: '',
    c3: 'b',
    c4: 'bb',
    c5: 'u',
    c6: ''
},
{
    id: 414,
    district: 77,
    firstName: 'Arne',
    lastName: 'Holtan',
    address: 'Sjøåsen',
    place: 'Namdalseid',
    c1: 'a-',
    c2: 'u',
    c3: 'a-g',
    c4: '',
    c5: 't',
    c6: ''
},
{
    id: 2169,
    district: 77,
    firstName: 'Elise Holtan Pavall',
    lastName: 'Årbogen',
    address: 'Sagavegen',
    place: 'Malm',
    c1: '',
    c2: 'p',
    c3: 'a',
    c4: '',
    c5: 'ht-',
    c6: 'a'
},
{
    id: 409,
    district: 77,
    firstName: 'Leif Arne',
    lastName: 'Jåma',
    address: 'Gotvatnet',
    place: 'Follafoss',
    c1: '',
    c2: '',
    c3: 'gg',
    c4: '',
    c5: 'u',
    c6: ''
},
{
    id: 410,
    district: 77,
    firstName: 'John Kristian',
    lastName: 'Jåma',
    address: 'Trongsundet',
    place: 'Mosvik',
    c1: 'aa',
    c2: '',
    c3: 'z-',
    c4: 'z-',
    c5: '',
    c6: 'aa'
},
{
    id: 3861,
    district: 77,
    firstName: 'Tor Daniel',
    lastName: 'Jåma',
    address: 'Gotvatnet',
    place: 'Follafoss',
    c1: '-a',
    c2: '',
    c3: 'a-',
    c4: '',
    c5: 'u',
    c6: 'g'
},
{
    id: 3863,
    district: 77,
    firstName: 'Lena',
    lastName: 'Haugen',
    address: 'Sjøåsen',
    place: 'Namdalseid',
    c1: '',
    c2: 'j',
    c3: 'g',
    c4: 'a',
    c5: 'p',
    c6: ''
},
{
    id: 404,
    district: 77,
    firstName: 'Arvid',
    lastName: 'Jåma',
    address: 'Verrastranda',
    place: 'Follafoss',
    c1: '',
    c2: 'u',
    c3: 'b',
    c4: 'bb',
    c5: '',
    c6: 'b'
},
{
    id: 4368,
    district: 77,
    firstName: 'Ingrid Maria',
    lastName: 'Jåma',
    address: '',
    place: 'Follafoss',
    c1: '',
    c2: 'q',
    c3: 'b',
    c4: 'b',
    c5: 'j',
    c6: ''
},
{
    id: 3862,
    district: 77,
    firstName: 'John',
    lastName: 'Haugen',
    address: 'Sjøåsen',
    place: 'Namdalseid',
    c1: 'b',
    c2: 't',
    c3: 'b',
    c4: 'a',
    c5: 'j',
    c6: ''
},
{
    id: 2161,
    district: 77,
    firstName: 'John Kristoffer',
    lastName: 'Jåma',
    address: 'Fjellet',
    place: 'Follafoss',
    c1: '',
    c2: 'th',
    c3: 'a',
    c4: '',
    c5: 'p',
    c6: ''
},
{
    id: 2160,
    district: 77,
    firstName: 'Sara Emilie',
    lastName: 'Jåma',
    address: 'Gotvatnet',
    place: 'Follafoss',
    c1: '',
    c2: '',
    c3: 'bb',
    c4: 'b',
    c5: '',
    c6: 'bb'
},
{
    id: 2159,
    district: 77,
    firstName: 'Maja Kristine',
    lastName: 'Jåma',
    address: 'Fjellet',
    place: 'Follafoss',
    c1: 'a',
    c2: '',
    c3: '',
    c4: '',
    c5: 't',
    c6: 'a'
},
{
    id: 517,
    district: 77,
    firstName: 'Sissel',
    lastName: 'Jåma',
    address: 'Verrastranda',
    place: 'Follafoss',
    c1: 'b-',
    c2: 'yt-',
    c3: 'b-',
    c4: '-y',
    c5: '',
    c6: ''
},
{
    id: 52,
    district: 77,
    firstName: 'Erling',
    lastName: 'Holtan',
    address: 'Sjøåsen',
    place: 'Namdalseid',
    c1: 'a-',
    c2: 'u',
    c3: 'a-g',
    c4: '',
    c5: '',
    c6: 'a'
},
]
